### ISSUE TITLE
Support For 12 Hour AM/PM format?

### ISSUE THREAD

**Issue by forrestbice** [wojtekmaj/react-datetime-picker#1]
Is there a way to configure the library to use 12 hour format rather than 24 hour format?

**Comment by wojtekmaj** [comment]
Not at the moment, but that's planned for development and the way is paved for this function to be implemented.

**Comment by forrestbice** [comment]
@wojtekmaj awesome! Is there an ETA for this?

**Comment by wojtekmaj** [comment]
I didn't set it, but now that I see demand I'll try to prioritize.

**Comment by forrestbice** [comment]
Sweet, we'd greatly appreciate it, this library is great!

**Comment by forrestbice** [comment]
@wojtekmaj any updates on this by chance?

**Comment by wojtekmaj** [comment]
Hi @forrestbice,
it's in the works :) Firstly it will be introduced in [React-Time-Picker](https://github.com/wojtekmaj/react-time-picker). You can track progress in wojtekmaj/react-time-picker#3. It's working so far, but I need to add extensive testing though.

**Comment by forrestbice** [comment]
Awesome @wojtekmaj! I just subscribed to the issue and associated PR in React-Time-Picker. Really looking forward to this merging and making its way to React-DateTime-Picker 🤘

**Comment by wojtekmaj** [comment]
Hope you'll still have some patience :) I am doing this only during my free time apart from being employed full time! 😱

**Comment by wojtekmaj** [comment]
Added in v1.4.0.

**Comment by forrestbice** [comment]
Awesome @wojtekmaj, thanks!

**Comment by shahar4** [comment]
Hey!

That's awesome that you allow this feature! How can I enable it?

Thanks!

**Comment by wojtekmaj** [comment]
@shahar4 It's enabled automatically for locales which tend to use AM/PM time. Just use `locale` prop to pass any locale which uses 12 hour time, for instance `en-US`.
