### ISSUE TITLE
issue with react-datetime-picker initial set-up

### ISSUE THREAD

**Issue by HirenPatel2791** [wojtekmaj/react-datetime-picker#10]
///React_Dashboard/node_modules/react-calendar/dist/Calendar.css:1
(function (exports, require, module, __filename, __dirname) { .react-calendar {
                                                              ^
SyntaxError: Unexpected token .
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)

**Comment by wojtekmaj** [comment]
Sounds like your Webpack (or other bundler) config is not set up properly for CSS files.
