### ISSUE TITLE
Changing date format

### ISSUE THREAD

**Issue by Fsocietykernel** [wojtekmaj/react-datetime-picker#100]
Hi,
I want to change the date  format to  yyyy-MM-dd'T'HH:mm:ss, I've tried using format attribute as follows
                                       <DateTimePicker
                                            format={"yyyy-MM-dd'T'HH:mm:ss"}
                                            onChange={this.onChange}
                                            value={this.state.pickdate}
                                        />
But the output is on this format "Wed Mar 25 2020 00:38:43 GMT+0530 (India Standard Time)"

Thanks.

**Comment by wojtekmaj** [comment]
Format applies to what's displayed on the picker. Picker always returns Date() object. The output you're looking at is just your browser's representation of Date() object.
