### ISSUE TITLE
Unable to find declaration file for module 'react-datetime-picker'

### ISSUE THREAD

**Issue by BaronSlayer** [wojtekmaj/react-datetime-picker#101]
import DateTimePicker from 'react-datetime-picker' produces the following error: "Could not find a declaration file for module 'react-datetime-picker'.  '...../react-datetime-picker/dist/entry.js' implicitly has 'any' type."

macOS Catalina 10.15.3
node: "13.1.0"
@babel/polyfill: "7.8.3"
react: "16.12.0"
react-datetime-picker: "2.9.0"

**Comment by wojtekmaj** [comment]
There are no TypeScript declarations shipped with React-DateTime-Picker. You can contribute, see #11.

**Comment by rickithadi** [comment]
@wojtekmaj are you working on this already? shall i file a PR?

**Comment by wojtekmaj** [comment]
This issue is closed. See discussion in #11 instead.
