### ISSUE TITLE
placeholder not working properly

### ISSUE THREAD

**Issue by heatherzhang080** [wojtekmaj/react-datetime-picker#106]
when the datetime object is null it's always showing a default time of 1/1/1970 10:00 am.

**Comment by wojtekmaj** [comment]
I was not able to reproduce this:

https://codesandbox.io/s/react-datetime-picker-null-value-z8me9

However, it's worth noting that if you wrap your date with `new Date(…)` without null checking, you will get the outcome described. This is because `new Date(null)` = `1970-01-01T00:00`.
