### ISSUE TITLE
Can type more than 4 digits into the year field.

### ISSUE THREAD

**Issue by ivanjonas** [wojtekmaj/react-datetime-picker#107]
Typing, for example, `04/14/20123` looks like it is accepted. However, by inspecting the hidden <input>, I can see that the real date value stored is `04/14/0123`.

**Comment by wojtekmaj** [comment]
Provided our civilisation will survive the coronavirus pandemic the year 20123 will come :D It's perfectly valid. You can limit it however to any 4-digit year, say 2100, using maxDate.

Can't do it for you - maybe someone would like to build a React-based sci-fi game placed in the distant future? ;)

**Comment by ivanjonas** [comment]
Fair enough. I thought it was broken because when I tried to get the hidden date field's value (with `$0.value` in the console) it didn't have the 5- or 6-digit year that I put into the form.

**Comment by JamieDixon** [comment]
What was the answer to this problem? We're seeing the same thing and it's unclear from this ticket what was said. Perhaps a comment was deleted that would bring more context to this ticket?

**Comment by ivanjonas** [comment]
Let me see if I can dig up the answer for you.

**Comment by ivanjonas** [comment]
Turns out it was pretty simple and straightforward. 

```jsx
const MAX_DATE = new Date('9999-12-31T23:59:59.999');

<DateTimePicker
  value={isValidDate ? value : new Date()}
  minDate={minValue}
  maxDate={MAX_DATE}
  ...
```

**Comment by JamieDixon** [comment]
@ivanjonas Perfect, thank you! I see now that the year 100,000 is perfectly acceptable as a year, although undesirable in our particular case. This solves the problem so thanks for coming back to me, I appreciate your time.
