### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by michaldudak** [wojtekmaj/react-datetime-picker#11]
Could you please consider creating type definitions for this library to make Typescript experience more pleasant?

**Comment by wojtekmaj** [comment]
Hello,
great idea :) I probably won't have time to do this this week, but if anyone would like to submit a PR before I do it, there's a sister package, [react-date-picker](https://github.com/wojtekmaj/react-date-picker/) which has it implemented, so a good chunk of it would be copy and paste :)

**Comment by oveddan** [comment]
I would like this too please.  Without types this is unusable in my project.

**Comment by l-Marty-l** [comment]
Without type definitions this great thing is useless to me.

**Comment by wojtekmaj** [comment]
You're free to contribute to DefinitelyTyped project. :)

**Comment by Talal916** [comment]
I'm gonna try to take a crack at it ^

**Comment by EmilyRagan** [comment]
@Talal916 I'm interested! If you need help, I'm willing to pitch in. If not, let me know when you finish it!

**Comment by plotka** [comment]
@Talal916 Do you have any update on this? I'm also available to help

**Comment by wojtekmaj** [comment]
You may take some inspiration from [React-Date-Picker's types](https://github.com/wojtekmaj/react-date-picker/blob/master/index.d.ts) as the packages are essentially siblings :)

**Comment by plotka** [comment]
@wojtekmaj  Is it ok if I create a new package in DefinitelyTyped for this?

**Comment by wojtekmaj** [comment]
I think that's always the workflow there, isn't it? I think that should be very much okay.

**Comment by Talal916** [comment]
Hi! So sorry! I ended up going with a different datetime picker. I'm willing to help out if there's still interest 

Sorry again, should have updated you guys on it!

**Comment by plotka** [comment]
> I think that's always the workflow there, isn't it? I think that should be very much okay.

@wojtekmaj  Not necessarily. You can have the file with the definitions inside of the package, as you have at the moment in [React-Date-Picker](https://github.com/wojtekmaj/react-date-picker/blob/master/index.d.ts), or you can create a new package in DefinitelyTyped, and in that case, the user will have to install the separate package with the types (or not if not using typescript).
I think the latter way is the standard and was suggesting doing it that way.

**Comment by wojtekmaj** [comment]
I'm very much for the latter!

**Comment by satvikpendem** [comment]
@Talal916 which one did you go with out of curiosity? I was also looking for types.

**Comment by Talal916** [comment]
@satvikpendem I ended up going with https://github.com/mui-org/material-ui-pickers
It actually doesn't have as nice of a keyboard support as this project, so I'm still considering switching to this.

**Comment by bdbmammoth** [comment]
I added a PR and I have a fork here if anyone needs it.

https://github.com/bdbmammoth/react-datetime-picker

**Comment by wojtekmaj** [comment]
Type definitions are to be added to DefinitelyTyped project. PRs with type definitions added directly to here won't be accepted as discussed above.

**Comment by ktrzos** [comment]
Hello! Something moved with this issue?

**Comment by martin-braun** [comment]
> Type definitions are to be added to DefinitelyTyped project. 

I think this statement is questionable. The DefinitelyTyped project exists for the case an author is not responsible, in my opinion. As a user it's always better to have the types within the primary package itself, because it causes less effort to install those.

**Comment by wojtekmaj** [comment]
React-DateTime-Picker is an open source project, provided "as is". Sure some PRs are raised but I'm it's only active maintainer. There's no one who volunteered to regularly update the entire family (React-Date-Picker, React-DateRange-Picker, React-DateTime-Picker, React-DateTimeRange-Picker, React-Time-Picker, React-TimeRange-Picker) with high quality typings. I'm not an expert in TypeScript, so I won't commit to something I can't deliver. It's better not to have typings than to have them wrong.

**Comment by paullam328** [comment]
The version by @bdbmammoth doesn't work, as index.d.ts disappears when being put in the root folder.
My version puts index.d.ts into the src folder.  It works like a charm for anyone who needs it: https://github.com/paullam328/react-datetime-picker

**Comment by alejandroiglesias** [comment]
No updates on this? Library still cannot be used with TypeScript?

**Comment by wojtekmaj** [comment]
You're more than welcome to contribute @alejandroiglesias! I just don't have the capacity or the knowledge to do this.

It's should be almost the same as typings for React-Date-Picker: https://github.com/wojtekmaj/react-date-picker/blob/main/index.d.ts

**Comment by alejandroiglesias** [comment]
@wojtekmaj unfortunately I don't have the knowledge to do this either, but I understand there was a PR for this? Not willing to include type definitions on this repo?

**Comment by princefishthrower** [comment]
For what it's worth, DefinitelyTyped has started to recommend types be added to their specific projects, but anyway, I have experience adding new type declarations to DefinitelyTyped, it's something I could do...

@wojtekmaj - is there a reason you won't accept a PR directly to this repo with a `index.d.ts` file? (As has apparently been done in `react-date-picker` already)

**Comment by wojtekmaj** [comment]
Actually I am unhappy about it being included in React-Date-Picker. There are no maintainers other than me. I don't know how to create good typings. So I'm getting issue reports for a thing I didn't write and can't maintain.

**Comment by princefishthrower** [comment]
@wojtekmaj - fair enough. I will move forward on DefinitelyTyped then. 👍

**Comment by princefishthrower** [comment]
Pull request opened over on DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57499

**Comment by suever** [comment]
> Pull request opened over on DefinitelyTyped: [DefinitelyTyped/DefinitelyTyped#57499](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57499)

Looks like this was merged so anyone interested in using this library with typescript can simply install the types:

```bash
yarn add @types/react-datetime-picker
# or npm install @types/react-datetime-picker
```

Do you think it's in a state where this issue can confidently be closed @wojtekmaj ?
