### ISSUE TITLE
react-calendar and react-datetime-picker on sampe app = style issues

### ISSUE THREAD

**Issue by maxtsh** [wojtekmaj/react-datetime-picker#112]
Hello, thanks for the wonderful tools you have created.

I have a problem with styling conflicts when I import two different packages. The first one is the react-calendar and the second one is react-datetime-picker.

they are in separate components but one of the components is imported inside the other with a condition. 

![image](https://user-images.githubusercontent.com/38842256/83786352-d4e8d780-a6a7-11ea-8f1e-417f07742298.png)

as I import the react-datetime-picker those above styles get persisted to the react-calendar!

**Comment by wojtekmaj** [comment]
You can import both components without styles and build your own as needed.
