### ISSUE TITLE
Can set date at Firefox and IE11. At IE11 time values look odd. At year input can put 6 digits

### ISSUE THREAD

**Issue by OleksandrPavlyshch** [wojtekmaj/react-datetime-picker#119]
Firefox and IE11 need to delete value before type.
Not correct year field workking.
Users can add leading zero almost everywhere like 012.
![image](https://user-images.githubusercontent.com/8597639/87423486-117eeb80-c5e3-11ea-9e2b-a161495aaf3a.png)

**Comment by Askholm** [comment]
We have the same issue with this component now. You cannot change the time unless you start by deleting the number. It is the same with the example use on the demo, so it is a legit issue with Firefox at least.

https://projects.wojtekmaj.pl/react-datetime-picker/

**Comment by gabdorf** [comment]
Same issue here. Neither clicking on a date nor typing a date works with Firefox.

**Comment by rvplauborg** [comment]
Reproduced on demo using Firefox 81.0. If fixed we could probably use the component, but we need it to work as smoothly as on Chrome where you can just input a number and it behaves as expected.

**Comment by dannypaz** [comment]
@Askholm @rvplauborg looks like this is related https://github.com/wojtekmaj/react-time-picker/issues/92

**Comment by wojtekmaj** [comment]
Sizing issues were long resolved. Regarding maximum number of numbers in year - yeah, 6 digits sounds just about right, provided that you didn't set maxDate to anything less than the year 10,000 AD.
