### ISSUE TITLE
overlaying issue

### ISSUE THREAD

**Issue by Huaoe** [wojtekmaj/react-datetime-picker#12]
Hi,
I have 2 react-datetime-picker stacked vertically and the 1st calendar is popping under the second one.
any clue ?
cheers

**Comment by foo4foo** [comment]
I have the same problem and was wondering if this release is live now.

**Comment by wojtekmaj** [comment]
Hello,
sorry for the wait. v1.3.2 just went out. Let me know if that fixed the issue for you.

**Comment by Huaoe** [comment]
Hi,
Yes it works,
thx
