### ISSUE TITLE
Using React-DateTime-Picker with styled-components

### ISSUE THREAD

**Issue by steinroe** [wojtekmaj/react-datetime-picker#122]
Hi,

thanks for this awesome package!

I am currently trying to apply custom styling to the input, but unfortunately, there is no className prop for the wrapper element. Hence, I cannot change the border style:

![Screenshot 2020-08-10 at 07 34 56](https://user-images.githubusercontent.com/19429600/89754396-fe751380-dadb-11ea-87ef-21f5c8e12784.png)

Is there a way to do this by passing a prop or do I have to overwrite the css?

Best
Philipp

**Comment by wojtekmaj** [comment]
Unfortunately there is a number of elements in React-DateTime-Picker which all would require passing props, and I don't think this is a good idea.

My suggestion for using React-DateTime-Picker with styled-components is treating React-DateTime-Picker like a native control: applying class name to the root element and work on "normal" classes from here, like so:

```js
const DatePicker = styled.div`
  .react-datetime-picker__wrapper {
    border: 1px solid red;
  }
`;
```

**Comment by steinroe** [comment]
Works for me, thanks for the hint!
