### ISSUE TITLE
Getting 12 hour format even with "ru-RU" locale and use12Hours={false} set

### ISSUE THREAD

**Issue by talentlessguy** [wojtekmaj/react-datetime-picker#125]
Hello, I'm trying to make this component use a 24 hour format w/o "AM/PM" but it still uses 12 hour format, despite setting the Russian locale and a special prop to disable the 12H format.

Here's the code:

```jsx
import React, { useState } from 'react'
import DatePicker from 'react-datetime-picker/dist/entry.nostyle'

const Calendar = ({ value }: { value?: string }) => {
  const [date, set] = useState(() => {
    if (!value) {
      const d = new Date()

      const year = d.getFullYear()
      const month = d.getMonth()
      const day = d.getDate()

      return new Date(year, month, day)
    } else {
      const parsed = Date.parse(value)

      return new Date(parsed)
    }
  })

  return (
    <DatePicker
      onChange={(d: Date) => {
        set(d)
        sessionStorage.setItem('date', d.toLocaleString('ru-RU'))
      }}
      value={date}
      locale="ru-RU"
      clearIcon={null}
      disableClock={true}
      format="dd.MM.yyyy hh:mm"
      use12Hours={false}
      name="date"
    />
  )
}
export default Calendar
```

And here's what I get when I try to type "15:25":

![Peek 2020-08-18 15-01](https://user-images.githubusercontent.com/35937217/90510515-cf0d7900-e163-11ea-9312-8cf93676fead.gif)

It turns into "03:25"

I need to remain being "15:25"

Am I missing something? Or it is a wrong locale bug?

If I try to format the date with `ru-RU` locale it works fine:

![image](https://user-images.githubusercontent.com/35937217/90510712-1e53a980-e164-11ea-850a-68dbc316a3ef.png)

**Comment by wojtekmaj** [comment]
`use12Hours`? Never heard of this prop...

Anyway, the reason for 12-hour clock being used is because you explicitly requested so by passing `hh` in `format` prop.

https://www.unicode.org/reports/tr35/tr35-dates.html#dfst-hour

**Comment by talentlessguy** [comment]
@wojtekmaj ok, how do I use the 24Hour format then? with the leading zeros, e.g.

`12:24`

**Comment by wojtekmaj** [comment]
I linked you the docs. It's literally under `hh` - you gotta use `HH`.

**Comment by talentlessguy** [comment]
@wojtekmaj doesn't work

![image](https://user-images.githubusercontent.com/35937217/90557350-03545a00-e1a3-11ea-9b39-1d847a85025a.png)


```jsx
import React, { useState } from 'react'
import DatePicker from 'react-datetime-picker/dist/entry.nostyle'

const Calendar = ({ value }: { value?: string }) => {
  const [date, set] = useState(() => {
    if (!value) {
      const d = new Date()

      const year = d.getFullYear()
      const month = d.getMonth()
      const day = d.getDate()

      return new Date(year, month, day, 12, 0)
    } else {
      const parsed = Date.parse(value)

      const d = new Date(parsed)

      return d
    }
  })

  return (
    <DatePicker
      onChange={(d: Date) => {
        set(d)
        sessionStorage.setItem('date', d.toLocaleString('ru-RU'))
      }}
      value={date}
      locale="ru-RU"
      clearIcon={null}
      disableClock={true}
      format="dd.MM.yyyy HH:mm"
      use12Hours={false}
      name="date"
      showLeadingZeros
    />
  )
}
export default Calendar
```

**Comment by talentlessguy** [comment]
@wojtekmaj thanks! it worked
