### ISSUE TITLE
No events occur when user enters invalid date

### ISSUE THREAD

**Issue by alexmnv** [wojtekmaj/react-datetime-picker#128]
How can the app know if the current date in the datetime-picker is valid or not? `onChange` event only occurs when the date entered by user is valid, otherwise no events are fired.

**Comment by wojtekmaj** [comment]
That is by design - native date picker also doesn't allow any invalid dates to be passed to onChange.
You can listen to onInvalid events, which bubble out of React-DateTime-Picker, so you can catch them on a custom container around it.
