### ISSUE TITLE
Error: Invalid date

### ISSUE THREAD

**Issue by marrkeri** [wojtekmaj/react-datetime-picker#13]
Hi,
I have problem with manual typing a year, which throws an error invalid date.
You can also simulate this error on page: http://projects.wojtekmaj.pl/react-datetime-picker/
Try to add 999 after year 2018. And when you will add 3rd "9" like this 201899 - error appears.

This is not a problem when you have passed validation and it is "red". So I think that this problem can be fixed with triggering validation after typing?

![image](https://user-images.githubusercontent.com/39760343/40708370-96dfdd88-63f3-11e8-9f48-e12b49866cb2.png)

![image](https://user-images.githubusercontent.com/39760343/40708109-e9767e40-63f2-11e8-9eb1-de5cc2cf8ff9.png)

![image](https://user-images.githubusercontent.com/39760343/40708519-f0a63736-63f3-11e8-8860-5818374c7e47.png)

**Comment by wojtekmaj** [comment]
Fixed in 1.3.4 Thanks!
