### ISSUE TITLE
Preset the timezone of DateTime selections

### ISSUE THREAD

**Issue by ralbach** [wojtekmaj/react-datetime-picker#135]
I'm looking at using react-datepicker for a personal project, but I was interested if it has the ability to preset the timezones.

I know localdatetimepicker is set based on a user's browser/OS but I'd like to make sure all times shown and selected by users are in UTC. 

I didn't see anything about that in documentation, is there a way to do that or would I need to add that capability in myself?

**Comment by wojtekmaj** [comment]
React-DateTime-Picker, just like the native date/time inputs in HTML, and like Date() in JavaScript, operate on local date and time. There's no concept of timezones, but you can fake it.

If you want to select dates in UTC, you will need to transform is back and forth - before passing to `value` and after receiving it from `onChange`.

So for example, if the user is located in Berlin, UTC+2, then for them to see midnight in React-DateTime-Picker you would need to pass a date which is 22:00 UTC of the day before. And the other way around: Upon receiving the date from `onChange`, you would need to add 2 hours to it to get UTC.

To detect current timezone offset for calculations, you can use [`Date.prototype.getTimezoneOffset()`](https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Obiekty/Date/getTimezoneOffset).
