### ISSUE TITLE
amPmAriaLabel not working

### ISSUE THREAD

**Issue by santilp95** [wojtekmaj/react-datetime-picker#136]
When I use the props amPmAriaLabel don't working 
<DateTimePicker
                        onChange={handleStartDateChange}
                        value={dateStar}
                        className="form-control"
                        amPmAriaLabel="Select AM/PM"
/>

**Comment by santilp95** [comment]
`<DateTimePicker
                        onChange={handleStartDateChange}
                        value={dateStar}
                        className="form-control"
                        amPmAriaLabel="Select AM/PM"
                    />`

**Comment by wojtekmaj** [comment]
Ran your code and it looks correct:

<img width="1083" alt="obraz" src="https://user-images.githubusercontent.com/5426427/98233934-fb18e900-1f5f-11eb-8952-309df6f09fbf.png">

**Comment by santilp95** [comment]
But it does not work for me, I attach images, the format remains in 24h
![1](https://user-images.githubusercontent.com/39132293/98306486-f66d2880-1f91-11eb-9436-ae06fe1e3e25.jpg)
![2](https://user-images.githubusercontent.com/39132293/98306488-f705bf00-1f91-11eb-8d4d-66b92b9d3bee.JPG)

**Comment by wojtekmaj** [comment]
Adding amPmAriaLabel does not make AM/PM field magically appear, it will only make it have ARIA-label, if it's rendered based on current configuration based on `locale` and `format`. Use `locale` and/or `format` to specify date format. Use `locale` to leave the format to us (so just provide e.g. `"en-US"`), or `format` if you want to have more control.

**Comment by tangducvi** [comment]
i have same problems. amPmAriaLabel doesn't work.

**Comment by DarkShark-RAz** [comment]
<DateTimePicker  onChange={onChange}  value={value}  format="dd-MM-y h:mm a"/>
By setting the format prop to "y-MM-dd h:mm a", you specify that the datetime picker should display the AM/PM component. The lowercase h represents the 12-hour clock format with AM/PM.
