### ISSUE TITLE
Is it possible to format weekdays? 

### ISSUE THREAD

**Issue by meganNelson03** [wojtekmaj/react-datetime-picker#139]
Hello! The demo demonstrates that weekdays can be reordered (ie, the first item in the weekday row is Sunday and not Monday, like in the default) . I've looked everywhere for a way to reorder the weekdays - how can I do this? 

Additionally, is it possible to rename the weekdays (shortened from Sun -> Su, Mon -> Mo, etc)? Thank you!

**Comment by wojtekmaj** [comment]
See [React-Calendar docs](https://github.com/wojtekmaj/react-calendar/). You can use `locale` to have the calendar type chosen for you based on locale, or `calendarType` if you want to explicitly set calendar type regardless of `locale`.
