### ISSUE TITLE
Is there any way to not open calendar or clock on input click?

### ISSUE THREAD

**Issue by yjw9012** [wojtekmaj/react-datetime-picker#14]
I thought I could use `isCalendarOpen` and `isClockOpen` but they seem behaving differently than I expected.

Any help would be appreciated, thank you!

**Comment by wojtekmaj** [comment]
Mmmm. I am aware of that and handling opening calendar/clock will be reworked. For now, I suggest hiding the clock with CSS, and hiding a button for opening it with `calendarIcon={null}`.
