### ISSUE TITLE
Missing leading zero for minutes

### ISSUE THREAD

**Issue by atheck** [wojtekmaj/react-datetime-picker#142]
Hi, after the last release the leading zero for minutes is missing for the initial value.

![Bildschirmfoto-20210315120504-157x46](https://user-images.githubusercontent.com/28619065/111143946-b55fd300-8586-11eb-81ce-a198a8414afe.png)

After typing some value (e.g. 4) it works. 

![Bildschirmfoto-20210315120648-173x55](https://user-images.githubusercontent.com/28619065/111144137-f3f58d80-8586-11eb-8f4f-c583a94e3916.png)

I'm using the format `"dd.MM.yyyy HH:mm"`

**Comment by wojtekmaj** [comment]
I'm not able to reproduce, leading zero is definitely there:

![image](https://user-images.githubusercontent.com/5426427/111146429-b3e3da00-8589-11eb-8689-e066e5a1537a.png)

https://codesandbox.io/s/react-datetime-picker-leading-zero-jcqxx?file=/src/index.jsx

**Comment by atheck** [comment]
That's right, but not if the value is zero.

https://codesandbox.io/s/react-datetime-picker-leading-zero-forked-1ueu7?file=/src/index.jsx

**Comment by mpcusack** [comment]
Could you release a new version? Thanks!
