### ISSUE TITLE
Next.js Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by mkoliba** [wojtekmaj/react-datetime-picker#143]
I tried to use component with react based Next.js v10 framework and run into this error. 
```
./node_modules/react-calendar/dist/Calendar.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@wojtekmaj/react-daterange-picker/dist/entry.js
```

The problem is that there is imported css file inside the node_module as explained in [https://err.sh/next.js/css-npm](https://err.sh/next.js/css-npm). 

Fastest fix would be to remove `import './DateTimePicker.css';` on line 8 in [src/entry.js](https://github.com/wojtekmaj/react-datetime-picker/blob/master/src/entry.js) and let user of library to import css their in application.

**Comment by Vespion** [comment]
A quick fix I've used is to import the version of the component without any styling and then manually import the default styles on the page.
`import DateTimePicker from 'react-datetime-picker/dist/entry.nostyle';
import 'react-calendar/dist/Calendar.css';
import 'react-clock/dist/Clock.css';
import 'react-datetime-picker/dist/DateTimePicker.css';`

**Comment by wojtekmaj** [comment]
That's how you should do it on Next.js actually :) Next version will not have styles automatically added.
