### ISSUE TITLE
Keyboard controls

### ISSUE THREAD

**Issue by dbollinger** [wojtekmaj/react-datetime-picker#144]
Is there any way to support aria-recommended keyboard controls? https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html

Using the tab key to progress through the entire calendar makes it challenging to quickly fill out forms that use this for date pickers.

**Comment by wojtekmaj** [comment]
Tracked in https://github.com/wojtekmaj/react-calendar, a dependency that renders the calendar in React-DateTime-Picker.
