### ISSUE TITLE
Let user only enter day month and time, no year

### ISSUE THREAD

**Issue by ZiangX** [wojtekmaj/react-datetime-picker#145]
Hi there, I would like to make a datetime picker that the user only needs to enter the day, month and time, no year. And I will default the year to 2021 behind the scene. Is it possible? 
![image](https://user-images.githubusercontent.com/33740669/113759406-06c13500-96e3-11eb-9f26-7d1be0afe8f8.png)

I tried the code below

     <DateTimePicker
        value={dateTime}
        onChange={setDateTime}
        format="dd/MM HH:mm"
      />

but it shows me an error of "Invalid date: Invalid Date". Could you give me some ideas of how to make it work, thank you!

**Comment by reymon359** [comment]
Hey @ZiangX I am facing a similar issue and would love to know if you found a solution to this 😄

**Comment by reymon359** [comment]
@wojtekmaj Thank you so much for taking the time and updating the library with the feature! You're awesome 😄
