### ISSUE TITLE
Invalid type when using arrow keys to pick values

### ISSUE THREAD

**Issue by jinmanm** [wojtekmaj/react-datetime-picker#146]
I get the following error when using the arrow keys to change dates.
```Failed prop type: Invalid prop `value` of type `number` supplied to `MinuteInput`, expected `string`.```

My onChange function updates a state value which then renders out in the DateTimePicker.

```
export const DateTimePickerDialog = (props) => {

    const [datetime, setDatetime] = useState(props.datetime);

    return (
        <DateTimePicker
            maxDate={props.maxDatetime}
            minDate={props.minDatetime}
            value={datetime}
            onChange={setDatetime}
        />
    );
};
```

I cannot control what values get passed to the child components so is there something im missing?

**Comment by ZiangX** [comment]
Same to me, as long as I use keyboard to type in the number, it shows me this warning

**Comment by ZiangX** [comment]
Are you using any kind of library to wrap this datepicker? I am using react-hook-form

**Comment by jinmanm** [comment]
the only library that would be wrapping it is redux im pretty sure; that is the actual component i copy and pasted

**Comment by jinmanm** [comment]
> Same to me, as long as I use keyboard to type in the number, it shows me this warning

For me it is no warning it is a full blown error that can cause crashes in an app

**Comment by lemihthien** [comment]
the same issue

**Comment by bilobom** [comment]
went ahead and created a [PR](https://github.com/wojtekmaj/react-datetime-picker/pull/151), hopefully this will resolve the warning

**Comment by jespadas** [comment]
I'm having the same issue...the app can't work ! 

There's no solution implemented  ?
