### ISSUE TITLE
Block typing, allow user to SELECT a date only

### ISSUE THREAD

**Issue by davifurtado** [wojtekmaj/react-datetime-picker#148]
Hello,

Is there anyway to block user from typing in the input and allow him to select the date only via calendar?

**Comment by davifurtado** [comment]
If anyone has the same problem, I found a "workaround" with onKeyDown property

simply create a onKeyDown function that will execute the preventDefault of the event, like this:

<DateTimePicker
          onChange={handleOnChange}
          value={value}
          onKeyDown={(e) => e.preventDefault()}
/>

This way the user will not be able to type anything. He can still click on the input to type but it won't type anything


It would be good to have this property in the documentation

Thank you

**Comment by wojtekmaj** [comment]
See #23 

See also https://github.com/wojtekmaj/react-date-picker/issues/174 - that's a feature that's still TODO.

**Comment by davifurtado** [comment]
> See #23
> 
> See also [wojtekmaj/react-date-picker#174](https://github.com/wojtekmaj/react-date-picker/issues/174) - that's a feature that's still TODO.


I think just putting on the documentation that the onKeyDown exists will help a lot of people. I discovered it by error and trial,
