### ISSUE TITLE
DateTimePicker shows only date on zh-CN locale

### ISSUE THREAD

**Issue by chingchiu169** [wojtekmaj/react-datetime-picker#15]
Just import and add <DateTimePicker /> in my react project.
Only date has been shown, but no time..sad.

However, when i add isClockOpen to true, it is correctly show the current time.

**Comment by wojtekmaj** [comment]
That's interesting... Can you show me your implementation? 🤔

**Comment by chingchiu169** [comment]
<div className="col-md-7 align-self-center">
                    <ol className="breadcrumb">
                        <li className="breadcrumb-item">
                            <button className="btn btn-info btn-sm" onClick={this.triggerModal}>Add</button>
                            <Popup open={this.state.modal.open} modal overlayStyle={{ background: "rgba(0, 0, 0, 0)" }} closeOnDocumentClick={false}>
                                <form style={{ margin: "15px" }}>
                                    <div className="form-body">
                                        {this.props.user.id == 1 &&
                                            <div className="form-group">
                                                <label className="col-sm-2 control-label">User</label>
                                                <select className="form-control input-rounded input-sm" name="type" onChange={this.handleInput} value={this.state.u_id}>
                                                    {options.map((option, index) => (
                                                        <option key={index} value={option.value}>{option.name}</option>
                                                    ))}
                                                </select>
                                            </div>
                                        }
                                        <div className="form-group">
                                            <label className="col-sm-2 control-label">Type</label>
                                            <select className="form-control input-rounded input-sm" name="type" onChange={this.handleInput} value={this.state.type}>
                                                <option value="1">Annual</option>
                                                <option value="2">Sick</option>
                                                <option value="3">Comp</option>
                                            </select>
                                        </div>
                                        <div className="form-group">
                                            <label className="col-sm-2 control-label">Reason</label>
                                            <input type="text" className="form-control input-rounded input-sm" name="title" onChange={this.handleInput} value={this.state.title} />
                                        </div>
                                        <div className="form-group">
                                            <label className="col-sm-2 control-label">Start</label>
                                            <DateTimePicker name="start" onChange={this.handleStartDate} value={this.state.start} showLeadingZeros={true} />
                                        </div>
                                        <div className="form-group">
                                            <label className="col-sm-2 control-label">End</label>
                                            <DateTimePicker name="end" onChange={this.handleEndDate} value={this.state.end} showLeadingZeros={true} />
                                        </div>
                                        <div className="form-group">
                                            <label className="col-sm-2 control-label">Duration</label>
                                            <input type="text" className="form-control input-rounded input-sm" name="duration" onChange={this.handleInput} value={this.state.duration} readOnly />
                                        </div>
                                    </div>
                                    <div className="form-actions text-right">
                                        <button type="submit" className="btn btn-success btn-sm" onClick={this.handleSubmit}> <i className="fa fa-check"></i> Save</button>
                                        <button type="submit" className="btn btn-inverse btn-sm" onClick={this.triggerModal}> Cancel</button>
                                    </div>
                                </form>
                            </Popup>
                        </li>
                    </ol>
                </div>

Here is it. Thank you

**Comment by wojtekmaj** [comment]
@chingchiu169 use ``` instead of ` :)

**Comment by chingchiu169** [comment]
@wojtekmaj Thank you!!! I am newbie of github and reactjs. Hope can fix this problem.

**Comment by wojtekmaj** [comment]
Your code actually looks really good. I am getting an impression you're having a styling issue. To check that, find the datetimepicker on a *rendered* page, and see if all inputs are there. They should be named day, month, year, hour etc. If they are all there, check your styling. Perhaps the input is simply too big to fit on your page and you need to play around a little?

**Comment by chingchiu169** [comment]
There are year, month and day. Hour, minutes and second were not rendered.

**Comment by wojtekmaj** [comment]
Hmmm... What browser are you on? What locale are you using?

If you run this in the console:

```js
new Intl.DateTimeFormat(
  window.navigator.language, 
  { hour: 'numeric', minute: 'numeric', second: 'numeric' }
).format(new Date());
```

Is a proper hour (like: `"10:48:37"`) returned?

**Comment by chingchiu169** [comment]
下午5:19:32
I am using chrome with version 67.0.3396.99

It's okay on your demo page too, but cannot work on my website.

**Comment by shigotoppoi** [comment]
I got same problem as @chingchiu169.
I just copyed the example from the npm site, and it only displayed year. month and day.
[https://www.npmjs.com/package/react-datetime-picker](url)
My chrome version is 67.0.3396.99 .

**Comment by wojtekmaj** [comment]
I figured that out. It's connected to a very different way of displaying "AM/PM" in time in zh-CN locale. The issue has been fixed, so the fix will be live with the next release.
