### ISSUE TITLE
Display datetime in UTC

### ISSUE THREAD

**Issue by CreaticDD** [wojtekmaj/react-datetime-picker#150]
Hi, awesome picker, but I need datetime displayed in UTC. Should we add an option {locale: false} to get the picker to work in UTC/GMT time?

**Comment by CreaticDD** [comment]
@wojtekmaj what are your thoughts on having the DateTimepicker work in UTC time - is that feasible?

**Comment by wojtekmaj** [comment]
Sorry, react-datetime-picker is trying to be on par with datetime-local native input. For UTC you'd have to manipulate the dates yourself to get rid of timezone offset.
