### ISSUE TITLE
Format time "h:mm" is crashing on change "invalid date".

### ISSUE THREAD

**Issue by bastian-hidalgo** [wojtekmaj/react-datetime-picker#152]
# How to reproduce

This error happens when a "time" format is given, I've been trying different formats, if you include the date, everything go well, its only with time formats, if you change the time with arrow keys or try to introduce something, it's invalid, I understand that is receiving a Date object and it's only a representation of the same, so the new values aren't valid.

# Example

### Invalid Date

`<DateTimePicker  format="h:mm a" ... />` 
_When its "onchanged" on the state, crashes the app._

### Valid Date

`<DateTimePicker format:="dd/MM/y" ... />` 

### Note: If this plugins always needs the date format as an obligation and the only way to do this is using `react-time-picker`, maybe could be included on the Docs.

Thank you for your awesome work.

**Comment by tabrez96** [comment]
Facing the same issue. It can be reproduced here: https://codesandbox.io/s/cool-dawn-3req0?file=/src/App.js
