### ISSUE TITLE
Calendar does not update when using inputs and a date is not set

### ISSUE THREAD

**Issue by piotrjanosz** [wojtekmaj/react-datetime-picker#157]
Hi Wojtek, thank you for the wonderful library.

I was wondering if it was possible to update the calendar view when user types only a part of a date (for example, just a year). It seems that currently it is only possible to make the calendar jump to a date when both date and time are set. 

We display year and month first on the project I am working on and I think it would help the user find the correct date faster.

**Steps to reproduce:**
1. Visit project's [website](https://projects.wojtekmaj.pl/react-datetime-picker/)
2. Change day, month, or year - notice the calendar gets updated.
3. Clear date and time by clicking on the clear button.
4. Set month or year - notice calendar does not get updated (for example, does not jump to the year that was typed in)

**Current behavior:** calendar view only gets updated when typing if date and time are first set.
**Desired behavior:** update calendar view whenever user types part of a date (for example, only the year is set).

**Comment by michaelholm** [comment]
Hello Wojtek

I am wondering the same thing - how can we make calendar update on input? Even after completing manual entry of date, and displaying the new date in the field, when clicking to expose the calendar, it's not updating. Is this expected behavior? How can we overcome this?

Thanks much,
Michael

**Comment by SaintPepsi** [comment]
@wojtekmaj Reopening, 
I'm experiencing the same issue, manually typing into the date picker when there's no date selected (--/--/----) and then clicking on the clear button doesn't clear the fields.
