### ISSUE TITLE
Suggestion: hideClock to use it as a date picker when time is unnecessary

### ISSUE THREAD

**Issue by Wrishi** [wojtekmaj/react-datetime-picker#159]
Can a prop like hideClock be introduced to remove the time picker component altogether? If so this plugin can be used as a date picker when time is unnecessary.

**Comment by garrettmaring** [comment]
The documentation states:

> The most detailed calendar view that the user shall see. View defined here also becomes the one on which clicking an item in the calendar will select a date and pass it to onChange. Can be "hour", "minute" or "second". Don't need hour picking? Try React-Date-Picker!

It's unfortunate that we would need to add another library just because `maxDetail: "day"` isn't supported.

![Screen Shot 2021-07-22 at 12 12 25 PM](https://user-images.githubusercontent.com/8270120/126696491-16f7104e-5da2-4a98-8867-aa220a560b5d.png)

**Comment by oohwooh** [comment]
Why not just use [wojtekmaj/react-date-picker](https://github.com/wojtekmaj/react-date-picker)?
