### ISSUE TITLE
showLeadingZeros not being respected

### ISSUE THREAD

**Issue by judemorrissey** [wojtekmaj/react-datetime-picker#160]
Observed on `3.3.0`

As title, the `showLeadingZeros` prop is not being respected when set to `false`, nor does it use the default value of `false` as stated in the docs for `react-datetime-picker`, but `react-date-picker` does properly when used by itself.

Thank you!

**Comment by nickb-WaPo** [comment]
I am having the same issue. `showLeadingZeros` does not seem to do anything

**Comment by wojtekmaj** [comment]
`showLeadingZeros` may force leading zeros to be shown if `format` didn't add them, but `format` may also cause leading zeros to be shown.
