### ISSUE TITLE
Month dropdown opens the calendar

### ISSUE THREAD

**Issue by shepparddean** [wojtekmaj/react-datetime-picker#166]
If you use the MMM or MMMM in the format for the date, the control has a drop down for a month selection which also opens the calendar control as well. Please refer to the attached screenshot which shows an arrow beside the month selection.

Is there an option to not render the drop down on the date month field?

![image](https://user-images.githubusercontent.com/225386/132897282-c231cf33-2d5f-41e0-90b2-e025ee936a92.png)

**Comment by Alberick** [comment]
Hi, @shepparddean 

Did you find a way to do that? I want to do the same

**Comment by wojtekmaj** [comment]
This was long fixed in 8f5d5d0c6fc79e3a6a3f94865e6497340d853456.
