### ISSUE TITLE
Warning: Failed prop type: Invalid prop value supplied to 'DateTimePicker.

### ISSUE THREAD

**Issue by jespadas** [wojtekmaj/react-datetime-picker#168]
I'm having like 25 errors and the whole app is crashing when I'm triying to change the event starting hour. Every time I got this :

1. `Warning: Failed prop type: Invalid prop value supplied to 'DateTimePicker.`
2. `Warning: Failed prop type: Invalid prop minDate of type object supplied to DateTimePicker, expected instance of Date`
3. `Warning: Failed prop type: Invalid prop value supplied to DateTimeInput.`
4. `Warning: Failed prop type: Invalid prop value supplied to Calendar`.
5. `Warning: Failed prop type: Invalid prop value supplied to Clock``.
...

I will be grateful if someone can help me.

**Comment by njeirath** [comment]
I'm seeing the same thing, looks like when setting either hours, minutes, or AM/PM the onChange is not emitting a Date object.

I've got a little test setup with something like this:
```
const [date, setDate] = useState(new Date())

<DateTimePicker
    value={date}
    onChange={(value: any) => {
        console.log(value)
        setDate(value)
    }}
/>
```

When changing a date component the console shows a proper Date object:
`Thu Oct 14 2021 15:44:16 GMT-0500 (Central Daylight Time)`

However when changing a time component it shows:
`SyntheticEvent {dispatchConfig: {…}, _targetInst: FiberNode, nativeEvent: InputEvent, type: 'change', target: input.react-datetime-picker__inputGroup__input.react-datetime-picker__inputGroup__hour, …}`

I'm assuming that on a time change it should also emit a Date object.

**Comment by douglasrcjames** [comment]
Hi!

I am getting a similar issue after updating to a recent build of react-datetime-picker. Error: `react_devtools_backend.js:4026 Warning: Failed prop type: Invalid prop 'value' supplied to 'DateTimeInput'.`

Below is my code using react-hook-forms Controller component and a few tertiary conditionals to test if the field is in seconds Timestamp for Firebase's Firestore. Before I found this bug, I was just passing `value={field.value}`, but I needed this conditional to actually display a default time if it failed.

Not really sure what changed with the recent updates that may have cause the time not to be displayed, any ideas?

```
<Controller
    control={setItemForm.control}
    name={itemColumn.key}
    rules={itemColumn.validators}
    render={({ field }) => {
        return (
            <DateTimePicker
                onChange={(date) => field.onChange(date)}
                value={(field?.value?.seconds ?? false) ? field.value.seconds : field.value ? field.value : null}
            />
        )
    }}
/>
```

Conversion snippet which takes the Firestore Timestamp format and converts to Javascript Date object for `DateTimePicker` to read: `toDatetimePicker = new Date(firestoreValue.seconds*1000);`

**Comment by djordje47** [comment]
I had the same problem, I am using redux instead of the react `useState` hook. 

**I think the trick is to pass the new Date instance.** 

So instead of doing this:
`... value={selectedTask.due_date ?? new Date()}`
I am doing this now and it works:
``` 
<DateTimePicker onChange={(value) => dispatch(setTaskDueDate(value))}
                          locale="sr"
                          value={selectedTask.due_date ? new Date(selectedTask.due_date) : new Date()}/>
```

If anyone still needs it. Cheers! :)
