### ISSUE TITLE
Clock staying open when the calendar  opened by clicking the calendar icon.

### ISSUE THREAD

**Issue by innocentamadi** [wojtekmaj/react-datetime-picker#17]
**Is this a feature request or a bug?**
A bug

**What's the issue?**
When the clock is open and I click on the calendar icon,  the clock doesn't go hidden so that the calendar can show. The calendar instead opens under the clock. 

<img width="317" alt="screen shot 2018-06-29 at 1 33 10 am" src="https://user-images.githubusercontent.com/12391897/42067107-71f4bda8-7b3c-11e8-8940-df3bafbe666d.png">

This behaviour remains so long as the user keeps clicking on the calendar icon to toggle the calendar on/off.

**What's the expected behavior?**
When the clock is open and I click the calendar icon, the clock widget should close so the calendar widget opens and takes up the space.

I can't think of a single use case where I'd want both widgets on the same date time picker at the same time.

**How can we replicate this issue?**
1. Visit a page on your project with the DateTimePicker component rendered on the dom.
2. Click on the time to show the clock widget.
4. Click on the calendar icon by the right to show the calendar widget. The calendar shows but below the clock. The clock stays open.
5. Click on the calendar icon  again to hide the calendar widget. The calendar widget hides. Clock remains open.

**Comment by innocentamadi** [comment]
Creating a fork of this amazing project right now so I can fix this on my fork. Would be happy to raise a PR here if this is confirmed a valid bug.

**Comment by innocentamadi** [comment]
@wojtekmaj you could close this once you have the changes merged in. I'm waiting for those changes :)

**Comment by wojtekmaj** [comment]
Hey @innocentamadi, I'm closing this as the new release is out :) Check out 1.3.5!
