### ISSUE TITLE
how can i add disabled date that already selected and can we change the styling for date picker column ?

### ISSUE THREAD

**Issue by Mahdi-Soultana** [wojtekmaj/react-datetime-picker#179]
Hi woktekmaj i really i have the honor  to ask you this question i want to use datet ime range picker and i want to know if i can make specific disabled time and range date and also if i can style columns date ?

**Comment by wojtekmaj** [comment]
You can't disable specific time. You can, however, specify minimum and maximum value, as described in README.

Regarding "styling columns date" I'm afraid I don't understand what you mean.
