### ISSUE TITLE
Improvements: support for European format (dd/mm/yyyy rather than American mm/dd/yyyy)

### ISSUE THREAD

**Issue by fabri86** [wojtekmaj/react-datetime-picker#19]
Cześć Wojtek, 
congratulations for this library. After customizing a bit the css I can say I am definitely very satisfied, it works well for my purposes.

I have however a request, I hope it is somehow achievable. 
In the project I am working on, the result data, shown to the user after filtering by date, present the information about the date in the European format, while the date time picker presents it under the American format only. This brings a little bit of confusion for an user which is inserting the date manually, without opening the calendar popup (And this is my case, since there are a lot of filters to be filled very quickly in our application).

Is there a way to include a prop for specifying the format we want the date to be shown in the picker after the user's selection or after the user's insertion? That would be great and would save me from the users' lynching :)

Cheers

**Comment by wojtekmaj** [comment]
Hi there,
let me explain how it works. 

1. React-DateTime-Picker is a "child" of React-Date-Picker, which depends on [React-Calendar's locale detection system](https://github.com/wojtekmaj/react-calendar/blob/master/src/shared/locales.js). This system tries to figure out which locale the user is using. You can overwrite automatic detection by passing `locale` prop to React-DateTime-Picker. For example, `locale="de-DE"` should result in DD/MM/YYYY format.
2. All three packages mentioned uses the locale information and [Intl.DateTimeFormat](https://developer.mozilla.org/pl/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) to figure out a format working best for a given locale. **This may result in different results in different browsers, depending on how well their implementation of Intl.DateTimeFormat in different locale is done**. However from my experience, modern browsers handle them all pretty well.

You can play around with locales and how they affect the inputs in my [test suite](http://projects.wojtekmaj.pl/react-datetime-picker/test/) :)

Tip: Whichever separator is figured out between inputs, for example `/` for en-US and `.` for de-DE, is also a key that can be used to type in the full date. So you can focus on the first input and just write `22.08.2018` and it should all go well :)

Hope this helps!

**Comment by fabri86** [comment]
Hi Wojciech,
Thanks a lot for your e
Clear explanation. I will write as well the answer on GitHub for future
needs.
Thanks a lot for your commitment in such a valid component.

Z poważaniem
Fabrizio

Il ven 6 lug 2018, 09:02 Wojciech Maj <notifications@github.com> ha scritto:
