### ISSUE TITLE
'react-datetime-picker--closed' className doesn't change to '--open' when calendar is open

### ISSUE THREAD

**Issue by tabrez96** [wojtekmaj/react-datetime-picker#190]
Description of the issue:
The baseClass 'react-datetimerange-picker' has a subClass which adds '--open' and '--closed' depending on the state of the calendar. It should render with 'react-datetimerange-picker--open' if calendar is open and 'react-datetimerange-picker--closed' if calendar is closed. But currently, it always renders with 'react-datetimerange-picker--closed' even if calendar is open.

It used to work in 3.0.0 but not working in 4.0.0

Demo using 4.0.0: https://stackblitz.com/edit/react-datetimepicker-xbe4uj?file=src%2FApp.js

**Comment by wojtekmaj** [comment]
Thanks, you're totally right, that's a regresion. Fixed!
