### ISSUE TITLE
Is there any way to prevent invalid values from being typed on hour/min/sec inputs?

### ISSUE THREAD

**Issue by yjw9012** [wojtekmaj/react-datetime-picker#20]
For example, when user types "25" on hour input, can I prevent the number from being rendered on the input?

BTW, this project is AWESOME!

cc. @wojtekmaj

**Comment by yjw9012** [comment]
@wojtekmaj Any help would be appreciated.

**Comment by wojtekmaj** [comment]
Hi there,
no, at the moment you cannot. We give the user visual feedback but the user has to correct the input on their own.

Looking at the behavior of native inputs, I think it should be done, though. I'll keep it on my list of potential enhancements.

I should also mention that the date has to be valid in order to be submitted via onChange, so you will never get an invalid date from the widget itself.

**Comment by yjw9012** [comment]
I see. Thank you!

**Comment by yjw9012** [comment]
@wojtekmaj Does your answer apply to react-time-picker as well, correct?

**Comment by wojtekmaj** [comment]
Yes, it does. To React-Date-Picker, React-Time-Picker, React-DateRange-Picker too :)

**Comment by yjw9012** [comment]
@wojtekmaj Thanks for your response!

**Comment by flq** [comment]
Hi @wojtekmaj 

> We give the user visual feedback but the user has to correct the input on their own.

I tried to see if there is some class or something applied when the component is currently in a state where the user has chosen an invalid date, alas, I can't find such a thing.

I think, stopping the user from entering invalid values is quite complicated and can become inflexible: Depending on the values of other fields, some values are OK while others are not.

What would help often, I think, is 
* if the component had a way to communicate that the current input is invalid according to the current settings.
* Some --invalid class applied to the whole component while the date entered is invalid.

**Comment by wojtekmaj** [comment]
It's out of the box in the platform ;) https://www.w3schools.com/cssref/sel_invalid.asp

**Comment by vmkarpenko** [comment]
Hi @wojtekmaj 
Is any updates for this issue?

**Comment by kurasaiteja** [comment]
> Hi there,
> no, at the moment you cannot. We give the user visual feedback but the user has to correct the input on their own.
> 
> Looking at the behavior of native inputs, I think it should be done, though. I'll keep it on my list of potential enhancements.
> 
> I should also mention that the date has to be valid in order to be submitted via onChange, so you will never get an invalid date from the widget itself.

How can we give the user visual feedback by showing a message?
