### ISSUE TITLE
Cannot integrate this picker into my project

### ISSUE THREAD

**Issue by geshenyi** [wojtekmaj/react-datetime-picker#22]
my package.json is like below
"react": "^15.6.1",
"react-datetime-picker": "1.0.1",
"react-dom": "^15.6.1"

Here is my code snippet
```
render() {
        let dateTime = new Date();
        return (
            <div>
                <div className="pure-g">
                    <div className="pure-u-1">
                        <Paper className="config-paper" zDepth={2}>
                            <div className="config-paper">
                                <DateTimePicker value={dateTime}/>
                            </div>
                        </Paper>
                    </div>
                </div>
            </div>
        )
    }
```

The page cannot be rendered properly, and in console i found some error messages

proxyConsole.js:56 
Warning: Failed prop type: The prop `className` is marked as required in `MonthInput`, but its value is `undefined`.
    in MonthInput (created by DateTimeInput)
    in DateTimeInput (created by DateTimePicker)
    in div (created by DateTimePicker)
    in div (created by DateTimePicker)
    in DateTimePicker (at multi-logs.js:31)
    in div (at multi-logs.js:30)
    in div (created by Paper)
    in Paper (at multi-logs.js:29)
    in div (at multi-logs.js:28)
    in div (at multi-logs.js:27)
    in div (at multi-logs.js:26)
    in MultiLogs (created by Route)
    in Route (created by withRouter(MultiLogs))
    in withRouter(MultiLogs) (created by Connect(withRouter(MultiLogs)))
    in Connect(withRouter(MultiLogs)) (created by Route)
    in Route (at App.js:86)
    in div (at App.js:80)
    in div (at App.js:76)
    in div (at App.js:75)
    in div (at App.js:71)
    in div (at App.js:60)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:59)
    in MuiThemeProvider (at App.js:58)
    in App (created by Connect(App))
    in Connect(App) (at index.js:17)
    in div (at index.js:16)
    in Provider (at index.js:15)
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:56
printWarning @ warning.js:33
warning @ warning.js:57
checkReactTypeSpec @ checkReactTypeSpec.js:78
validatePropTypes @ ReactElementValidator.js:160
createElement @ ReactElementValidator.js:214
renderMonth @ DateTimeInput.js:252
(anonymous) @ DateTimeInput.js:325
renderCustomDateInputs @ DateTimeInput.js:320
render @ DateTimeInput.js:399
(anonymous) @ ReactCompositeComponent.js:793
measureLifeCyclePerf @ ReactCompositeComponent.js:73
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:792
_renderValidatedComponent @ ReactCompositeComponent.js:819
performInitialMount @ ReactCompositeComponent.js:359
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountComponentIntoNode @ ReactMount.js:102
perform @ Transaction.js:141
batchedMountComponentIntoNode @ ReactMount.js:124
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
_renderNewRootComponent @ ReactMount.js:317
_renderSubtreeIntoContainer @ ReactMount.js:399
render @ ReactMount.js:420
./src/index.js @ index.js:15
__webpack_require__ @ bootstrap 410fcd7b7fbcfbcece90:669
fn @ bootstrap 410fcd7b7fbcfbcece90:87
0 @ registerServiceWorker.js:108
__webpack_require__ @ bootstrap 410fcd7b7fbcfbcece90:669
(anonymous) @ bootstrap 410fcd7b7fbcfbcece90:715
(anonymous) @ bootstrap 410fcd7b7fbcfbcece90:715
proxyConsole.js:56 Warning: Failed prop type: The prop `className` is marked as required in `DayInput`, but its value is `undefined`.
    in DayInput (created by DateTimeInput)
    in DateTimeInput (created by DateTimePicker)
    in div (created by DateTimePicker)
    in div (created by DateTimePicker)
    in DateTimePicker (at multi-logs.js:31)
    in div (at multi-logs.js:30)
    in div (created by Paper)
    in Paper (at multi-logs.js:29)
    in div (at multi-logs.js:28)
    in div (at multi-logs.js:27)
    in div (at multi-logs.js:26)
    in MultiLogs (created by Route)
    in Route (created by withRouter(MultiLogs))
    in withRouter(MultiLogs) (created by Connect(withRouter(MultiLogs)))
    in Connect(withRouter(MultiLogs)) (created by Route)
    in Route (at App.js:86)
    in div (at App.js:80)
    in div (at App.js:76)
    in div (at App.js:75)
    in div (at App.js:71)
    in div (at App.js:60)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:59)
    in MuiThemeProvider (at App.js:58)
    in App (created by Connect(App))
    in Connect(App) (at index.js:17)
    in div (at index.js:16)
    in Provider (at index.js:15)
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:56
printWarning @ warning.js:33
warning @ warning.js:57
checkReactTypeSpec @ checkReactTypeSpec.js:78
validatePropTypes @ ReactElementValidator.js:160
createElement @ ReactElementValidator.js:214
renderDay @ DateTimeInput.js:241
(anonymous) @ DateTimeInput.js:323
renderCustomDateInputs @ DateTimeInput.js:320
render @ DateTimeInput.js:399
(anonymous) @ ReactCompositeComponent.js:793
measureLifeCyclePerf @ ReactCompositeComponent.js:73
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:792
_renderValidatedComponent @ ReactCompositeComponent.js:819
performInitialMount @ ReactCompositeComponent.js:359
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountComponentIntoNode @ ReactMount.js:102
perform @ Transaction.js:141
batchedMountComponentIntoNode @ ReactMount.js:124
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
_renderNewRootComponent @ ReactMount.js:317
_renderSubtreeIntoContainer @ ReactMount.js:399
render @ ReactMount.js:420
./src/index.js @ index.js:15
__webpack_require__ @ bootstrap 410fcd7b7fbcfbcece90:669
fn @ bootstrap 410fcd7b7fbcfbcece90:87
0 @ registerServiceWorker.js:108
__webpack_require__ @ bootstrap 410fcd7b7fbcfbcece90:669
(anonymous) @ bootstrap 410fcd7b7fbcfbcece90:715
(anonymous) @ bootstrap 410fcd7b7fbcfbcece90:715
proxyConsole.js:56 Warning: Failed prop type: The prop `className` is marked as required in `YearInput`, but its value is `undefined`.
    in YearInput (created by DateTimeInput)
    in DateTimeInput (created by DateTimePicker)
    in div (created by DateTimePicker)
    in div (created by DateTimePicker)
    in DateTimePicker (at multi-logs.js:31)
    in div (at multi-logs.js:30)
    in div (created by Paper)
    in Paper (at multi-logs.js:29)
    in div (at multi-logs.js:28)
    in div (at multi-logs.js:27)
    in div (at multi-logs.js:26)
    in MultiLogs (created by Route)
    in Route (created by withRouter(MultiLogs))
    in withRouter(MultiLogs) (created by Connect(withRouter(MultiLogs)))
    in Connect(withRouter(MultiLogs)) (created by Route)
    in Route (at App.js:86)
    in div (at App.js:80)
    in div (at App.js:76)
    in div (at App.js:75)
    in div (at App.js:71)
    in div (at App.js:60)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:59)
    in MuiThemeProvider (at App.js:58)
    in App (created by Connect(App))
    in Connect(App) (at index.js:17)
    in div (at index.js:16)
    in Provider (at index.js:15)
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:56
printWarning @ warning.js:33
warning @ warning.js:57
checkReactTypeSpec @ checkReactTypeSpec.js:78
validatePropTypes @ ReactElementValidator.js:160
createElement @ ReactElementValidator.js:214
renderYear @ DateTimeInput.js:262
(anonymous) @ DateTimeInput.js:327
renderCustomDateInputs @ DateTimeInput.js:320
render @ DateTimeInput.js:399
(anonymous) @ ReactCompositeComponent.js:793
measureLifeCyclePerf @ ReactCompositeComponent.js:73
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:792
_renderValidatedComponent @ ReactCompositeComponent.js:819
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountComponentIntoNode @ ReactMount.js:102
perform @ Transaction.js:141
batchedMountComponentIntoNode @ ReactMount.js:124
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
_renderNewRootComponent @ ReactMount.js:317
_renderSubtreeIntoContainer @ ReactMount.js:399
render @ ReactMount.js:420
./src/index.js @ index.js:15
__webpack_require__ @ bootstrap 410fcd7b7fbcfbcece90:669
fn @ bootstrap 410fcd7b7fbcfbcece90:87
0 @ registerServiceWorker.js:108
__webpack_require__ @ bootstrap 410fcd7b7fbcfbcece90:669
(anonymous) @ bootstrap 410fcd7b7fbcfbcece90:715
(anonymous) @ bootstrap 410fcd7b7fbcfbcece90:715
proxyConsole.js:56 Warning: Failed prop type: The prop `className` is marked as required in `HourInput`, but its value is `undefined`.
    in HourInput (created by DateTimeInput)
    in DateTimeInput (created by DateTimePicker)
    in div (created by DateTimePicker)
    in div (created by DateTimePicker)
    in DateTimePicker (at multi-logs.js:31)
    in div (at multi-logs.js:30)
    in div (created by Paper)
    in Paper (at multi-logs.js:29)
    in div (at multi-logs.js:28)
    in div (at multi-logs.js:27)
    in div (at multi-logs.js:26)
    in MultiLogs (created by Route)
    in Route (created by withRouter(MultiLogs))
    in withRouter(MultiLogs) (created by Connect(withRouter(MultiLogs)))
    in Connect(withRouter(MultiLogs)) (created by Route)
    in Route (at App.js:86)
    in div (at App.js:80)
    in div (at App.js:76)
    in div (at App.js:75)
    in div (at App.js:71)
    in div (at App.js:60)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:59)
    in MuiThemeProvider (at App.js:58)
    in App (created by Connect(App))
    in Connect(App) (at index.js:17)
    in div (at index.js:16)
    in Provider (at index.js:15)
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:56
printWarning @ warning.js:33
warning @ warning.js:57
checkReactTypeSpec @ checkReactTypeSpec.js:78
validatePropTypes @ ReactElementValidator.js:160
createElement @ ReactElementValidator.js:214
renderHour @ DateTimeInput.js:271
(anonymous) @ DateTimeInput.js:357
renderCustomTimeInputs @ DateTimeInput.js:352
render @ DateTimeInput.js:401
(anonymous) @ ReactCompositeComponent.js:793
measureLifeCyclePerf @ ReactCompositeComponent.js:73
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:792
_renderValidatedComponent @ ReactCompositeComponent.js:819
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountComponentIntoNode @ ReactMount.js:102
perform @ Transaction.js:141
batchedMountComponentIntoNode @ ReactMount.js:124
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
_renderNewRootComponent @ ReactMount.js:317
_renderSubtreeIntoContainer @ ReactMount.js:399
render @ ReactMount.js:420
./src/index.js @ index.js:15
__webpack_require__ @ bootstrap 410fcd7b7fbcfbcece90:669
fn @ bootstrap 410fcd7b7fbcfbcece90:87
0 @ registerServiceWorker.js:108
__webpack_require__ @ bootstrap 410fcd7b7fbcfbcece90:669
(anonymous) @ bootstrap 410fcd7b7fbcfbcece90:715
(anonymous) @ bootstrap 410fcd7b7fbcfbcece90:715
proxyConsole.js:56 Warning: Failed prop type: The prop `className` is marked as required in `MinuteInput`, but its value is `undefined`.
    in MinuteInput (created by DateTimeInput)
    in DateTimeInput (created by DateTimePicker)
    in div (created by DateTimePicker)
    in div (created by DateTimePicker)
    in DateTimePicker (at multi-logs.js:31)
    in div (at multi-logs.js:30)
    in div (created by Paper)
    in Paper (at multi-logs.js:29)
    in div (at multi-logs.js:28)
    in div (at multi-logs.js:27)
    in div (at multi-logs.js:26)
    in MultiLogs (created by Route)
    in Route (created by withRouter(MultiLogs))
    in withRouter(MultiLogs) (created by Connect(withRouter(MultiLogs)))
    in Connect(withRouter(MultiLogs)) (created by Route)
    in Route (at App.js:86)
    in div (at App.js:80)
    in div (at App.js:76)
    in div (at App.js:75)
    in div (at App.js:71)
    in div (at App.js:60)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:59)
    in MuiThemeProvider (at App.js:58)
    in App (created by Connect(App))
    in Connect(App) (at index.js:17)
    in div (at index.js:16)
    in Provider (at index.js:15)
__stack_frame_overlay_proxy_console__ @ proxyConsole.js:56
printWarning @ warning.js:33
warning @ warning.js:57
checkReactTypeSpec @ checkReactTypeSpec.js:78
validatePropTypes @ ReactElementValidator.js:160
createElement @ ReactElementValidator.js:214
renderMinute @ DateTimeInput.js:287
(anonymous) @ DateTimeInput.js:359
renderCustomTimeInputs @ DateTimeInput.js:352
render @ DateTimeInput.js:401
(anonymous) @ ReactCompositeComponent.js:793
measureLifeCyclePerf @ ReactCompositeComponent.js:73
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:792
_renderValidatedComponent @ ReactCompositeComponent.js:819
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountComponentIntoNode @ ReactMount.js:102
perform @ Transaction.js:141
batchedMountComponentIntoNode @ ReactMount.js:124
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
_renderNewRootComponent @ ReactMount.js:317
_renderSubtreeIntoContainer @ ReactMount.js:399
render @ ReactMount.js:420
./src/index.js @ index.js:15
__webpack_require__ @ bootstrap 410fcd7b7fbcfbcece90:669
fn @ bootstrap 410fcd7b7fbcfbcece90:87
0 @ registerServiceWorker.js:108
__webpack_require__ @ bootstrap 410fcd7b7fbcfbcece90:669
(anonymous) @ bootstrap 410fcd7b7fbcfbcece90:715
(anonymous) @ bootstrap 410fcd7b7fbcfbcece90:715
invariant.js:42 Uncaught Error: MonthInput.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
    at invariant (invariant.js:42)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:828)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:359)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:234)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js:701)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:520)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:234)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js:701)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:520)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:234)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js:701)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:520)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:234)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js:701)

**Comment by Tzaphkiel** [comment]
I got the same issue:

```js
warning: Failed prop type: The prop `className` is marked as required in `MonthInput`, but its value is `undefined`.
    in MonthInput (created by DateTimeInput)
    in DateTimeInput (created by DateTimePicker)
    in div (created by DateTimePicker)
    in div (created by DateTimePicker)
    in DateTimePicker (at NewsEditorMod.jsx:48)
    in div (at NewsEditorMod.jsx:47)
    in div (at NewsEditorMod.jsx:43)
    in div (at NewsEditorMod.jsx:42)
    in div (at NewsEditorMod.jsx:41)
    in Route (at NewsEditorMod.jsx:40)
    in div (at NewsEditorMod.jsx:22)
    in Route (at NewsEditorMod.jsx:21)
    in NewsEditorModComp (created by Connect(NewsEditorModComp))
    in Connect(NewsEditorModComp) (created by Route)
    in Route (at App.jsx:36)
    in Switch (at App.jsx:32)
    in div (at App.jsx:29)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at App.jsx:28)
    in Provider (at App.jsx:27)
    in AppComp (created by Connect(AppComp))
    in Connect(AppComp) (at index.js:22)
```
for all kinds of {day, month, hour, ...) input.

with the following dependencies:
```json
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "react-scripts": "1.1.4",
    "react-datetime-picker": "1.0.1",
```
