### ISSUE TITLE
Again, use [React-Date-Picker](/wojtekmaj/react-date-picker) :) It belongs to the same family of projects, and because of that using these two at the same time **will not make your bundle heavier**.

### ISSUE THREAD

**Issue by Arifullahkhan1** [wojtekmaj/react-datetime-picker#226]
[React-Date-Picker](https://github.com/wojtekmaj/react-date-picker)

it is not  working for me either . i used Time Piker

**Comment by wojtekmaj** [comment]
"Not working" is not helpful at all. Closing since I can't make any action out of this. Happy to reopen if more information is provided on what specifically isn't working.

**Comment by Arifullahkhan1** [comment]
<div>Date: {cleaningDate.toDateString()}</div>

**Comment by wojtekmaj** [comment]
react-datepicker is not my package. You should seek support in https://github.com/Hacker0x01/react-datepicker repo.
