### ISSUE TITLE
Setting locale to en-AU doesn't display option to select AM/PM

### ISSUE THREAD

**Issue by FarKotw** [wojtekmaj/react-datetime-picker#24]
Setting locale to en-AU it is not displaying AM/PM in time selection. Here is my code.

`<DateTimePicker onChange={this.updateStartDT} value={this.state.StartDT} locale="en-AU" use12Hours="false"/>`

I am using chrome for testing. Also setting use12Hours="false" not displaying time in 24 hour format.

**Comment by wojtekmaj** [comment]
Fixed in 1.4.2. Thank you!

**Comment by FarKotw** [comment]
Thank you, working now.
