### ISSUE TITLE
The specified value "false" is not a valid number

### ISSUE THREAD

**Issue by mattheweberhardt** [wojtekmaj/react-datetime-picker#25]
I don't get this on your demo page, but I see it on my install, so it might be a conflict with something?
When I click the clear icon or I set the value to null programaticly, the following warning is triggered:

>The specified value "false" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?

![image](https://user-images.githubusercontent.com/39489374/43648103-1a4307e8-96ff-11e8-8e5c-ce4606625691.png)

It does work, even with the warning, the input box is cleared and it can be used again. i've stripped mine down to mimic your example code:
`import React from 'react';
import DateTimePicker from 'react-datetime-picker';

export default class MyDatePicker extends React.Component {

	constructor(props) {
		super(props);

		this.state = {
			date: new Date(),
		}
	}

	onChange = date => this.setState({ date })

	render() {

		return(
			<DateTimePicker
				onChange={this.onChange}
				value={this.state.date}
			/>
		);
	}
}
`

this is my package.json

>   "dependencies": {
    "npm": "^6.3.0",
    "react": "^16.4.2",
    "react-burger-menu": "^2.5.2",
    "react-date-picker": "^6.11.2",
    "react-datetime-picker": "^1.4.1",
    "react-dom": "^16.4.2",
    "react-input-mask": "^2.0.2",
    "react-loadable": "^5.4.0",
    "react-notifications": "^1.4.3",
    "react-overlays": "^0.8.3",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4",
    "react-table": "^6.8.6",
    "react-tippy": "^1.2.2",
    "recharts": "^1.1.0",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.1.1"
  },

**Comment by wojtekmaj** [comment]
Hi,
could you expand the error message from the console so I could see where this message is exactly coming from?

**Comment by mattheweberhardt** [comment]
No problem. I'm hoping this isn't from something else I have installed and is wasting your time. Let me know if I can provide anything else

![image](https://user-images.githubusercontent.com/39489374/43657042-37d21eaa-971a-11e8-9656-fbc376352ba9.png)

**Comment by wojtekmaj** [comment]
Hi again, I revisited this issue and I can't really reproduce it. There is a chance you're using an old version which does not play well with React for some reason. Although I revisited the archived code for this version you were using and I don't see a way for `false` to appear in an input value.

**Comment by mattheweberhardt** [comment]
Thank you for looking at it again. since i submitted this i've upgraded both react and your plugin and now the error is gone :-) 

thank you for your time on this library and the date and time picker one. it's appreciated!
