### ISSUE TITLE
Unable to hide the clock

### ISSUE THREAD

**Issue by twinraven** [wojtekmaj/react-datetime-picker#26]
I'd like to be able to disable the clock, so it doesn't appear when editing the time.

However the `isClockOpen` prop doesn't seem to control this, as I thought it would; looking at the code, this doesn't appear to be a feature, unless I'm missing something?

If this is not currently a feature, nor in development (and is something you think would be a positive addition) please let me know - I'd be interested in trying to add this.

**Comment by wojtekmaj** [comment]
Hello,
yes, this would be a valueable addition. Please feel free to make a PR.
