### ISSUE TITLE
maxDate provided but still allows date which is more then the range

### ISSUE THREAD

**Issue by djdheeraj53** [wojtekmaj/react-datetime-picker#274]
We provide maxDate in react-datetime-picker but when we try to add date by input into text box then its allowing it. Moreover in input its showing input value but its not triggered in onChange. Due to this we can't fix it from our end too

**Comment by wojtekmaj** [comment]
It may be possible for the user to enter invalid date, but it shouldn't be accepted as a valid input and should not trigger onChange, just like the native date picker.

**Comment by djdheeraj53** [comment]
but its not in-appropriate behavior. in input it will show invalid value but actually value is different. Can u please provide some solution for it. I have found other date picker which is handing it https://reactdatepicker.com/#example-min-date.
Please check it once

**Comment by wojtekmaj** [comment]
It's mimicking native date picker behavior, try it. You can trick it into having invalid value displayed (perhaps harder than with my package), and this won't trigger onChange event.
