### ISSUE TITLE
Instead of the clock, I need a drop-down to select the time 

### ISSUE THREAD

**Issue by MuppaHarsha** [wojtekmaj/react-datetime-picker#304]
import React, { useState } from 'react';
import DateTimePicker from 'react-datetime-picker';

export default function App() {
  const [date, setDate] = useState(new Date());

  function handleChange(newDate) {
    setDate(newDate);
  }

  return (
    <div>
      <DateTimePicker
        onChange={handleChange}
        value={date}
        time={true}
      />
    </div>
  );
};
This is my code. I need a time drop-down to select the time. but I am unable to make that
![image](https://user-images.githubusercontent.com/90750222/218971840-4cafdc64-f695-435e-a48e-ac74626d0e3a.png)

**Comment by MuppaHarsha** [comment]
![Capture](https://github.com/wojtekmaj/react-datetime-picker/assets/90750222/a8c420aa-4de6-4431-9226-a81d821bd398)
I need this type of drop-down.

**Comment by sambailor** [comment]
Please have support for seconds as well. Something like [this](https://mui.com/x/react-date-pickers/date-time-picker/#:~:text=change%20this%20behavior%3A-,%22year%22%22%2C%20%22month%22%2C%20%22day%22%2C%20%22hours%22%2C%20%22minutes%22%20and%20%22seconds%22,-%22day%22%2C%20%22hours%22) from mui time picker but in 24 or 12 hour format.

**Comment by surveyIpangram** [comment]
Please provide this feature , we are waiting

**Comment by JanderSilv** [comment]
This is a desired feature by my team as well.
