### ISSUE TITLE
Time components ignore minDate/maxDate parameters

### ISSUE THREAD

**Issue by sqlninja** [wojtekmaj/react-datetime-picker#31]
So setting a minDate works great for keeping user from choosing a date in the past, but there isn't a minTime to keep the user from choosing a time in the past.

Can this be added?

**Comment by wojtekmaj** [comment]
Sure! That should have worked. There won't be a separate minTime parameter, the datetime picker will simply prevent the user from choosing a time before the one specified in minDate, if they have chosen the date from minDate.

**Comment by sqlninja** [comment]
Thanks for the reply, just so I can temper my expectations, any estimation as to when that should be functional or is it currently just a feature request for the backlog?

**Comment by davidbejarcaceres** [comment]
Any news about this change? I had the same problem, just checks for the Date not the Time and does not pass minTime prop to react-time-picker component.
