### ISSUE TITLE
Input should select current value on focus

### ISSUE THREAD

**Issue by marcoancona** [wojtekmaj/react-datetime-picker#32]
Hi there! This looks like a great project.
I noticed a behavior that looks odd to me.
If I click on one of the time components, let's say the month, and I start typing, instead of replacing the current content with the new value it add the new value to the value that is already there (making it not valid, of course). 
In the following example, I clicked between the 2 and 018 in the year field, and typed "2019". I would expect it to just replace the year instead of producing this result (see date-time picker on macOS default calendar app). This is easily achieved by selecting the all text when the user clicks in any position. Maybe this behavior can also be toggled with some setting. I would be happy to contribute for this.
<img width="534" alt="screen shot 2018-10-06 at 11 04 19" src="https://user-images.githubusercontent.com/2278117/46569580-9c837a00-c957-11e8-9e17-25b85b386464.png">

**Comment by wojtekmaj** [comment]
Closed via recent changes in React-Date-Picker & React-Time-Picker, input providers for this package. Expect it to be fixed in the nearest release.

**Comment by marcoancona** [comment]
Great, thanks!
