### ISSUE TITLE
Typing the value with "0" at the beginning causes value to be cut

### ISSUE THREAD

**Issue by marcoancona** [wojtekmaj/react-datetime-picker#33]
This looks like a big to me. If I type “01” as month, it will convert it in “001”. Still seems to work but I cannot read the month anymore as the text overflows.

![933fc0c6-a5cc-4e4e-9c3d-5a97fba9a60b](https://user-images.githubusercontent.com/2278117/46570023-6990b480-c95e-11e8-9eb1-2a4cafce3428.jpeg)

**Comment by wojtekmaj** [comment]
Hello,
leading zeros in number input elements are indeed tricky to work with. I've managed to fix an issue that caused the inputs to miss cut off one number, though.

Fixed that, expect it to be included in the next release!
