### ISSUE TITLE
Not able to import `DateTimePickerProps`.

### ISSUE THREAD

**Issue by Rixtho** [wojtekmaj/react-datetime-picker#351]
I ran `pnpm i -S react-datetime-picker` and `pnpm i -S @types/react-datetime-picker` but I am not able to use `DateTimePickerProps`. It shows the following error message:
> TS2724: '"react-datetime-picker"' has no exported member named 'DateTimePickerProps'. Did you mean 'DateTimePicker'?

But the downloaded type definitions do seem to contain the correct exported members:
![image](https://user-images.githubusercontent.com/74471193/231098560-cfbbdff5-89b4-484d-935f-4f6af90b0cc1.png)

**Comment by wojtekmaj** [comment]
> pnpm i -S @types/react-datetime-picker

React-DateTime-Picker is native TypeScript and does not need external types as per newest version that's why the external types are not working anymore. However, you're right that types are not exported. You can use:

`React.ComponentProps<typeof DateTimePicker>`

**Comment by Rixtho** [comment]
Thanks. I hadn't noticed that update. I saw that I also need to manually import the custom styles. How does that work?
`import 'react-datetime-picker/dist/DateTimePicker.css'` and then `className: 'react-datetime-picker'`?
