### ISSUE TITLE
Build failing with error "Creating an optimized production build... Failed to compile. Module not found"

### ISSUE THREAD

**Issue by bebarkbaloch** [wojtekmaj/react-datetime-picker#353]
Creating an optimized production build...
Failed to compile.
Module not found: Error: Can't resolve 'react-date-picker/dist/DateInput/DayInput' in '/opt/atlassian/pipelines/agent/build/node_modules/react-datetime-picker/dist'

In pipeline its showing above package error .
any solution for that?

**Comment by wojtekmaj** [comment]
Sounds like you're using an old version.

**Comment by bebarkbaloch** [comment]
> Sounds like you're using an old version.
Im using this  version   "react-datetime-picker": "^4.2.1",

**Comment by bebarkbaloch** [comment]
Upgrading to latest version resolved that issue.
Thanks for help @wojtekmaj
