### ISSUE TITLE
Possibility to use only input field

### ISSUE THREAD

**Issue by marcoancona** [wojtekmaj/react-datetime-picker#36]
Can this component be used without the actual calendar picker (only the input field)?
I have my own calendar widget and I would like to use display it when the input field gets on focus, is it possible? I don't see onFocus/onBlur events.

**Comment by wojtekmaj** [comment]
You should be able to use `onFocus` starting with v1.7.0.

You can disable calendar icon by setting `calendarIcon` to `null`. You can't hide the calendar other than with CSS, but it's a valuable feedback!

**Comment by Dgarc359** [comment]
@wojtekmaj hello, I am trying to access `onFocus` and `onBlur` as well, for the overall datetime picker. I'm currently having the issue where every change in the values pushed into the picker is changing state, I would like to only change my state when the user has finished populating all the values. I'm using version 3.x of this library. I notice there's focus and blur events for the calendar and clock, but I can't seem to pinpoint or attach one to the overall component. Is there a current pattern for dealing with this use case?
