### ISSUE TITLE
Typing of `onChange` prop is broken

### ISSUE THREAD

**Issue by DreierF** [wojtekmaj/react-datetime-picker#375]
Since version 5.1.0 the type of the `onChange` prop is in inferred to have an `any` parameter. AFAICS this is due to the `EventProps` that overwrites the explicitly defined `onChange?: (value: Value) => void;`.

<img width="548" alt="image" src="https://github.com/wojtekmaj/react-datetime-picker/assets/5631865/a5c8ee74-632f-444b-8c46-100b9216bf11">

Reproduction: https://stackblitz.com/edit/react-ts-8nkjse?file=App.tsx

**Comment by wojtekmaj** [comment]
Thanks for the heads up, and more importantly for a good repro. I'm happy to say this has been resolved in 5.2.0.
