### ISSUE TITLE
[Firefox 62.0.3 macOS High Sierra] - vertical height changes/grows on click

### ISSUE THREAD

**Issue by owl-93** [wojtekmaj/react-datetime-picker#38]
The input field of the picker grows when the user clicks inside of the box. See gif

https://gfycat.com/ifr/WaryGroundedIrishdraughthorse

**Comment by wojtekmaj** [comment]
I can't help you with a component that does not belong to this package, but as a hint, try `position: fixed` on `.react-calendar` if you need to render component in a modal with `overflow: hidden`.
