### ISSUE TITLE
DateInput, MonthInput, MonthSelect y YearInput not be resolved

### ISSUE THREAD

**Issue by ErickCodigo** [wojtekmaj/react-datetime-picker#388]
![Error al resolver los paquetes internos](https://github.com/wojtekmaj/react-datetime-picker/assets/48195961/f37920a6-92e0-4182-a10d-791b18d2d274)

We recently updated a package from the company where I work and since then I get the following error. I literally did not move anything in the version or its use in the application but when trying to generate the build, I get the error in the image, please help me.

I use node version 14.18.0 
react-datetime-picker version is 4.1.1
command to generate the build is tsc && vite build

![Uso del paquete](https://github.com/wojtekmaj/react-datetime-picker/assets/48195961/c3fbd063-9067-47fb-abe8-8878f7b432c2)

Also in a week image I share the only use that we give in the application.

**Comment by wojtekmaj** [comment]
As you may imagine, I cannot reproduce this in my test environment. Would you be able to share a reproducible example?

**Comment by ErickCodigo** [comment]
> As you may imagine, I cannot reproduce this in my test environment. Would you be able to share a reproducible example?

I just made this project replicating the error: https://github.com/ErickCodigo/test-datetime-react

**Comment by ErickCodigo** [comment]
Did you happen to check the error?

**Comment by wojtekmaj** [comment]
I did not yet, but thank you so much for this. Will look at the earliest opportunity.

**Comment by wojtekmaj** [comment]
Oh, okay, here's the deal. This old version of react-datetime-picker uses old import paths to the components you've mentioned. If you installed it near the time of release, and used lockfile, it would continue to work.

Since then though, react-date-picker and react-time-picker this package depends on got restructured internals and this package also had to be updated to account for that.

You have two options:
- Use Yarn resolutions / npm [name to find but it's there] to force older version of react-date-picker and react-time-picker to be installed
- Update package to the latest version

**Comment by ErickCodigo** [comment]
> Oh, okay, here's the deal. This is an old version of react-datetime-picker that uses old import paths to the internal components you've mentioned it imports from external dependencies. If you installed it near the time of release, and used a lockfile, it would have continued to work. Specifically, you would have react-date-picker 9.1.0 and react-time-picker 5.1.0 installed.
> 
> Since then though, react-date-picker and react-time-picker this package depends on got restructured internals and this package also had to be updated to account for that. These changes were not included in 4.x release.
> 
> You have two options:
> - Use Yarn resolutions / npm overrides to force older version of react-date-picker (9.1.0) and react-time-picker (5.1.0) to be installed alongside react-datetime-picker
> - Update package to the latest version
> Hope this helps!

It worked perfectly, thank you very much
