### ISSUE TITLE
Focus time entry after date is selected

### ISSUE THREAD

**Issue by sambailor** [wojtekmaj/react-datetime-picker#389]
Is there a way to focus on time entry automatically once the date is selected via the props? Such that when a user selects a date, they can see that they're being prompted to enter a time. I'm assuming this can be done with your current props but I haven't figured out a way to yet.

The act of clicking a date and then clicking into the time field to edit it seems cumbersome to me.

**Comment by wojtekmaj** [comment]
Not that I know of. Theoretically you could add a listener higher up the DOM tree, see if all date inputs are filled and automatically focus time input, but nothing specific in react-datetime-picker is available to aid with this.
