### ISSUE TITLE
in AM/PM mode I can select a datetime less than minDate

### ISSUE THREAD

**Issue by stubar** [wojtekmaj/react-datetime-picker#39]
I am trying to have a date picker that only allows future datetimes.

It is now 6:10pm, I set the minDate to ```minDate={new Date()}```.

If I set the date picker to today, select the hour input and press up to 12, my picked datetime is 12pm which is in the past.

It feels like the hour input should start at 12 and go upto 11 ie 12 1 2 3 4 5 6 7 8 9 10 11, so pushing up always goes to the future.  Pretty sure that's not possible with a regular HTML5 number input with min max attributes, but am sure it could be done in React.

**Comment by stubar** [comment]
Thanks, understood.  FYI I have managed to work around this for now by adding 

```
    if (minDate && minDate > date) date = minDate;
    if (maxDate && maxDate < date) date = maxDate;
``` in my wrapper component date change handler.

**Comment by chinanderm** [comment]
Has there been any progress on this bug?
