### ISSUE TITLE
How do I change my format to the Unicode Z format?

### ISSUE THREAD

**Issue by douglasrcjames** [wojtekmaj/react-datetime-picker#399]
I am currently using Prisma with Next.js, Yup, and TypeScript. Looks like the format used between all these libraries is Unicode Z, such as `2023-09-29T07:00:00.000Z`. The format currently being output from my Datetime component is as such `Sat Sep 30 2023 00:00:00 GMT-0700 (Pacific Daylight Time)`. How would I use the `format` prop to modify the react-datetime-picker output/inputs timestamps? Some of my `onChange` and `value` setting was scaffolding after trying to fix this issue, but figured using the `format` prop would be more ideal!

**Current Component:**
```
<Controller
                name={fieldKey}
                control={control}
                render={({ field }) => {
                    return (
                        <DateTimePicker
                            disabled={disabled}
                            calendarType={"gregory"}
                            minDate={allowPrevDates ? null : new Date()}
                            onChange={(date: any) => field.onChange(date ? new Date(date) : null)}
                            $error={errors[fieldKey]}
                            value={field?.value ? new Date(field.value) : null}
                        />
                    )
                }}
            />
```

**Comment by wojtekmaj** [comment]
`Sat Sep 30 2023 00:00:00 GMT-0700 (Pacific Daylight Time)` is not the format you're getting the value in. That's a visual representation of `Date` object in your browser. 

Regarding your question how to get ISO string - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
