### ISSUE TITLE
Collision with bottom --above-label css needs to be added

### ISSUE THREAD

**Issue by ascendtradingdevelopment** [wojtekmaj/react-datetime-picker#4]
When the datetime picker collides with the bottom of the screen it adding the --above-label tag to the classname, however there is no css in the DateTimePicker.less file to support rendering the picker above the label. 

Solution is to add the following to DateTimePicker.less: 

&--above-label {
      bottom: 100%;
      top: auto;
    }

**Comment by wojtekmaj** [comment]
I think there was some misunderstanding because of my poor naming :)
Picker itself is a "label" for the calendar. --above-label signalizes that the calendar collided with the bottom of the screen and decided to open above the input.
