### ISSUE TITLE
Input are not properly sized in some scenarios

### ISSUE THREAD

**Issue by marcoancona** [wojtekmaj/react-datetime-picker#40]
I am experience a problem when the component is loaded with a provided `value`. Only the first digit of day, month, year, as well as time, is displayed (see image).
<img width="153" alt="screenshot 2018-10-29 at 17 34 58" src="https://user-images.githubusercontent.com/2278117/47667966-8c9e3500-dba7-11e8-9b2d-3e8c9f4f8fef.png">

The input fields are then correctly resized either by changing the `value` prop, or by clicking on one of the fields.

**Comment by wojtekmaj** [comment]
Hmm, it looks like auto-expanding fields are not working correctly 🤔  Are you using default styling or you have decided to write your own ones?

**Comment by marcoancona** [comment]
I am using the default style (to be precise I load the `.nostyle` but the default CSS style is already loaded separately at that time).
I am using this within a (https://v0.material-ui.com/#/components/popover)[Material-UI Popover]. Might this be the case? 
Also trying to debug this, I found that `getBoundingClientRect().width` in `updateInputWidth()` returns 0. I wonder if this method is called to early in the rendering pipeline.

**Comment by marcoancona** [comment]
Ok, I realized that if I use the `<Popover animated={false}>` the problem does not occur. My guess is that the first `updateInputWidth()` is called while the `Popover` component is transitioning (a scale transformation, I guess) and the `span` used as a reference has a width of zero. 

I guess this is quite an edge case, so I can also find my own workaround if you are not interested in supporting this scenario.

**Comment by wojtekmaj** [comment]
I'm actually interested as this affects some other more common scenarios, like rendering input before a font is loaded. I just need a better solution than just measuring everything every .1 seconds :/
