### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by wiryonolau** [wojtekmaj/react-datetime-picker#405]
can you share webpack config for this ?
I have problem loading the lib with non nodejs project 

perhaps an umd package ?

Error when loading page
```
Uncaught TypeError: The specifier “react” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.
```

**Comment by wojtekmaj** [comment]
Looks like you may have import map in your app 🤔 Is that right?

https://discourse.threejs.org/t/firefox-importmap-error-the-specifier-three-was-a-bare/48855

**Comment by wiryonolau** [comment]
Hi everything works now. I'm a bit late in implementing webpack, it works flawlessly now
