### ISSUE TITLE
Add className variable for input wrapper

### ISSUE THREAD

**Issue by kennedybaird** [wojtekmaj/react-datetime-picker#41]
So, I just spent some time trying to get this looking nice in my project.

![screenshot_20181112_174310](https://user-images.githubusercontent.com/20593811/48327241-72ce1900-e6a2-11e8-8511-36c17af783d0.png)

All I needed to do was be able to apply a class to the outer wrapper et voila:

![screenshot_20181112_174240](https://user-images.githubusercontent.com/20593811/48327246-78c3fa00-e6a2-11e8-8f32-7c23ffd64dbf.png)

Have you thought about adding this as an option? It seems like a no-brainer with regards to compatibility.

**Comment by wojtekmaj** [comment]
Hi,
DateTimePicker already accepts `className` prop.

**Comment by kennedybaird** [comment]
I'm suggesting an additional `className` prop, called `wrapperClassName`.

This would go at lines 168 & 174 of `DateTimePicker.jsx` as so:

```javascript
renderInputs() {
    const {
      calendarIcon,
      clearIcon,
      disabled,
      locale,
      maxDetail,
      maxDate,
      minDate,
      name,
      required,
      showLeadingZeros,
      value,
      wrapperClassName,
    } = this.props;

    const { isCalendarOpen, isClockOpen } = this.state;

    return (
      <div className={`${baseClassName}__wrapper ${wrapperClassName}`}>
 ```

**Comment by lcsixp** [comment]
I'm also very interested in this kind of feature.
