### ISSUE TITLE
Support custom hour format other than locale

### ISSUE THREAD

**Issue by cbfrank** [wojtekmaj/react-datetime-picker#42]
The date time picker use locale to determine if the hour format is 12 or 24, but this is not always the best way. for example, if the locale is "zh-Hans-CN" it will use 12 hours format, but in China the 24 hours format is the primary time format.
further more, even use 12 hours format, the time result is also not correct for "zh-Hans-CN" 
The Intl.DateTimeFormat with "zh-Hans-CN" locale will format the time "15:00:00" to "下午3:00:00" where (下午 is pm), but datetime picker finally dispaly the time as 3:00:00.
Is it possible we add an option such as "h24", and if it has value, just pass it to the formatDate function, and in this function, check if the parameter "h24" has value or not, and set "hour12" to true or false when call new ` Intl.DateTimeFormat`

Thanks

**Comment by wojtekmaj** [comment]
Hi,
I have bad and good news.

The bad:
The decision behind using `locale` as a "single source of truth" regarding whether or not to display some inputs, and how they should be aligned, is going to stay. There will be no other way to get a 24-hour clock than using a locale which uses 24-hour clock.

The good:
The "am/pm" picker not displaying for `zh-CN` locale is a bug and will be fixed.

**Comment by wojtekmaj** [comment]
@cbfrank Please check out `react-datetime-picker@2.1.0` and tell me what you think.

**Comment by cbfrank** [comment]
@wojtekmaj 2.1.1 works, thanks!
