### ISSUE TITLE
Calendar not closing when input is blurred using a keyboard

### ISSUE THREAD

**Issue by needpower** [wojtekmaj/react-datetime-picker#43]
Preconditions: 
- 2 date-time pickers are given, one after another;
- input focus is on the second date-time picker, calendar is open.

Use `Shift+Tab` to navigate to the first picker.

Expected result: calendar only for the first picker is displayed.
Actual result: calendars for both fields are displayed.

When use just `Tab` to navigate between pickers, only one calendar is displayed.

Video example: https://www.dropbox.com/s/hl87otpyq46z79z/Screen%20Recording%202018-11-16%20at%2015.01.11.mov?dl=0

**Comment by wojtekmaj** [comment]
Thanks for reporting. Fix will be out with the next release of React-Date-Picker, React-DateTime-Picker and React-Time-Picker.
