### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientHeight' of null

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-datetime-picker#44]
There is a fatal error causing pages to crash when the picker is clicked:
Uncaught TypeError: Cannot read property 'clientHeight' of null

I think it perhaps is related to the difficulty with sizing?

_Originally posted by @Phamiliarize in https://github.com/wojtekmaj/react-datetime-picker/issues/40#issuecomment-440114332_

**Comment by wojtekmaj** [comment]
@Phamiliarize try `v2.1.1`, there were a couple of fixes regarding that error in v2.1.x branch.

**Comment by Phamiliarize** [comment]
I apologize, actually I clicked the wrong repository. I am using react-datetimerange-picker...

I assume though that it is more or less the same, and bugs relating to sizing in that component would be fixed out of 2.1.1 branch.

**Comment by wojtekmaj** [comment]
Yeah, it was a race condition that may or may not have occurred. It is fixed anyway ;) React-DateTimeRange-Picker will be released soon, after the next bugfix release of React-DateTime-Picker, to have everything aligned.
