### ISSUE TITLE
Better ux when manually entering numbers

### ISSUE THREAD

**Issue by bigblind** [wojtekmaj/react-datetime-picker#49]
It would be cool if the component handled some cases better when manually entering the digits.

- When a value has been typed, focus should automatically move to the next field
- When I enter a 0 in the month or date field, the value is set to 00 as expected, but when I then enter a different digit, it is just appended, like `003`. 3-digit numbers shouldn't be possible there.

I think the date time control shown in Chrome for `input type="datetime-local"` is a great example to model this component's behavior on. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

Also notice how it automatically skips  the month and year parts in the first example because the month and year of the maximum and minimum values have the same month and year.

I've looked over the code base to try and understand it to see if I could help and contribute to these improvements, but there's a lot to dig into. Still, I'll keep reading code :).

**Comment by wojtekmaj** [comment]
Hi,
this has been implemented in v2.5.0 (7a55aaa). Go check it out! :)
