### ISSUE TITLE
how to change the position of a calendar

### ISSUE THREAD

**Issue by adityabatra240** [wojtekmaj/react-datetime-picker#50]
let  me give you brief info, while i try to change the year/month/date, calendar got popped up in upward direction, which got cut off on my screen, so i am not able to see full calendar, i want to change the position of my calendar in downward direction, could you please help me on that?

**Comment by wojtekmaj** [comment]
Hi,
next update should be way smarter about the way we display the calendar, thanks to [React-Fit](/wojtekmaj/react-fit) implemented.
I'm still working on it to give the developers even more control, but so far I don't have anything to share.

**Comment by adityabatra240** [comment]
Thanks a lot for your prompt reply. Will look for your next release.

Thanks,
Aditya

**Comment by Ahmad-Abo-Saa** [comment]
any update on this issue? is there a work around that we can do ?

**Comment by wojtekmaj** [comment]
React-Fit is already implemented a long time ago in e507711d5c8cc3e1a88ff704be311357e3e63c7a.

Please see https://github.com/wojtekmaj/react-date-picker/issues/229 for more details on how to handle this with React-Fit.
