### ISSUE TITLE
Can't enter hour lower than 12

### ISSUE THREAD

**Issue by jellz** [wojtekmaj/react-datetime-picker#52]
![](https://i.imgur.com/TumLGD1.png)
This happens when using an hour lower than 12. It doesn't let me input 24-hour times like 13, 14, etc, so I figure it's supposed to be 12-hour, yet 12-hour doesn't work properly.

**Comment by jellz** [comment]
And now that isn't happening. I wonder if it will start happening again

**Comment by wojtekmaj** [comment]
Looks like you specified minDate to me.

**Comment by jellz** [comment]
minDate is set to `new Date()`

**Comment by wojtekmaj** [comment]
So that should be it; new Date() equals now, so if there's 14:38 on the clock, you shouldn't be able to select hour lower than 14 provided that selected day is today, and minute lower than 38, provided that selected hour is 14 today.

**Comment by jellz** [comment]
Seems it was my error. Thank you.

**Comment by jellz** [comment]
Right now it is 10:57 AM on 03/20/2019 (en-US) and I am trying to select 2:20 PM, it is saying "Value must be greater than or equal to 10"

**Comment by wojtekmaj** [comment]
You should select PM first in order to be able to select hour from valid PM range.
