### ISSUE TITLE
AM/PM difference not used with `max/minDate`

### ISSUE THREAD

**Issue by tlyon3** [wojtekmaj/react-datetime-picker#53]
There is an issue when using two pickers for a range (start, end). 

I've setup my component to have a `startDate` and an `endDate` in my state. 
```
state = {
   endDate: new Date(),
   startDate: new Date()
}
```
These are changed via the `onChange ` method on their respective `datetime-picker`s. 

In addition, the start picker has a `maxDate` value of `state.endDate`, and the end picker has a `minDate` value of `state.startDate`

Now the problem: if I set the start to be `01/01/2019 7:00 AM`, I cannot set the end to be `01/01/2019 4:00 PM`

I can, however, set `endDate` to be `01/01/2019 8:00 PM`. It seems like it's comparing the hour only and checking the end hour (4) < start hour (7) without taking AM/PM into consideration.

Here is a setup of the situation:
https://codesandbox.io/embed/r44vx6jxr4

**Comment by wojtekmaj** [comment]
Hi,
thanks for reporting this. You're right - AM/PM isn't taken into consideration. This will be fixed in the next release.
