### ISSUE TITLE
Error: Failed to get hours from date: 2018-11-14T06:00:00.000Z

### ISSUE THREAD

**Issue by iyobo** [wojtekmaj/react-datetime-picker#54]
A date string format like "2018-11-14T06:00:00.000Z" is not being datified, even though this is the purest form of a date string as far as Javascript is concerned.

```
dates.js:25 Uncaught (in promise) Error: Failed to get hours from date: 2018-11-14T06:00:00.000Z.
    at getHours (dates.js:25)
    at getDerivedStateFromProps (DateTimeInput.js:646)
    at applyDerivedStateFromProps (react-dom.development.js:11265)
    at mountClassInstance (react-dom.development.js:11583)
    at updateClassComponent (react-dom.development.js:13145)
    at beginWork (react-dom.development.js:13824)
    at performUnitOfWork (react-dom.development.js:15863)
    at workLoop (react-dom.development.js:15902)
    at renderRoot (react-dom.development.js:15942)
    at performWorkOnRoot (react-dom.development.js:16560)
```

**Comment by wojtekmaj** [comment]
Definitely not intended, thanks for reporting. Fix on the way.

**Comment by jojoblaze** [comment]
I downloaded the npm package today (version 2.3.0) but there is still the same bug. It wasn't released yet on npm?

**Comment by iyobo** [comment]
Yeah It's a pretty foundational bug. It can't handle raw JavaScript dates
which is the wine point of the component. It should be npm version patch'd,
and npm publish'd as soon as it's fixed.

**Comment by gchokhonelidze** [comment]
"Failed to get hours from date", same issue on maxDate

**Comment by wojtekmaj** [comment]
@gchokhonelidze Do you have repro?

**Comment by gchokhonelidze** [comment]
> @gchokhonelidze Do you have repro?

Hello, I passed date object and issue solved, thanks.

**Comment by wojtekmaj** [comment]
Still I'd appreciate the code you were having issues with :) It might help a lot of people.

**Comment by remybroun** [comment]
I am running into this (2022)

**Comment by scott210189** [comment]
Error: Failed to get hours from date: [object Object]. im getting this too

**Comment by rajrkane** [comment]
I still seem to get a similar error.
`Failed to get human-readable month from date: 2024-03-01T07:00:00.000Z.`
