### ISSUE TITLE
Only am/pm time when custom format is given

### ISSUE THREAD

**Issue by CapsE** [wojtekmaj/react-datetime-picker#63]
When I'm using the datetime-picker without custom format I can type times like 18:30 no problem. Once I set a custom format and type the number 18 into the input it changes to 6 automatically. This is still the correct time but since I don't want to display am/pm it's not correct in my use case. Any ideas how to fix this?

**Comment by wojtekmaj** [comment]
Hm, the date should not be automatically changed in any way. What format precisely are you using?

**Comment by wojtekmaj** [comment]
Oh, that's simple! Refer to this document:

https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table

As you can see, `hh` refers to hour in AM/PM format. You're looking for `HH`. :)
