### ISSUE TITLE
Unable to resolve "react-calendar/dist/Calendar.css" from "node_modules/react-datetime-picker/dist/entry.js"

### ISSUE THREAD

**Issue by robinpaulson** [wojtekmaj/react-datetime-picker#64]
After including it in my react project, like this:
import DateTimePicker from 'react-datetime-picker';

react-native v0.59

react-calendar is not in the node_modules folder within react-datetime-picker, but in the project node_modules folder. 

node 11.15
npm 6.7.0

**Comment by wojtekmaj** [comment]
Hi,
this project is not designed for React Native. Sorry!

**Comment by abdu355** [comment]
Also happens in NextJS

**Comment by delrosariotanny** [comment]
This also happens in NextJs. has anyone found the solution for this?

**Comment by wojtekmaj** [comment]
How about importing React-DateTime-Picker without the styles, and import the styles yourself?

**Comment by mtliendo** [comment]
☝🏽 Thanks @wojtekmaj that did it

**Comment by Aleksandar1932** [comment]
use `import DateTimePicker from "react-datetime-picker/dist/entry.nostyle";`

**Comment by taufikmuharrom** [comment]
thank you for the solution @Aleksandar1932 , its work for me!
