### ISSUE TITLE
TypeError: (0 , _utils.between) is not a function

### ISSUE THREAD

**Issue by cpoulsen** [wojtekmaj/react-datetime-picker#71]
Getting this with version 1.0.1 and React 15.6.2

import DateTimePicker from 'react-datetime-picker';

<DateTimePicker
   onChange={this.handleDateChange}
   value={new Date()} />

**Comment by wojtekmaj** [comment]
1.x is not supported anymore, especially a version this old. Try the newest 1.x version or even better - just *the* newest version available.

**Comment by cpoulsen** [comment]
From what i read in the documentation React >15.5 requires 1.0.1 which is listed as supported?

Trying version 2.2.1 results in TypeError: Cannot read property 'toLocaleString' with new Date() as the value.

**Comment by wojtekmaj** [comment]
Ah, right. By "newest supported" I meant "supported by this React version". As stated in MIT license, project is distributed "as is", and any support is done by volunteers (usually me).

Try to lock other dependencies to the versions stated in 1.0.1 lockfile, especially react-calendar, react-date-picker.
