### ISSUE TITLE
Pass name into onChange handler

### ISSUE THREAD

**Issue by insivika** [wojtekmaj/react-datetime-picker#74]
How do I pass the "name" prop into the onChange handler. It seems to only return the actual date/time which is very limiting.

**Comment by wojtekmaj** [comment]
Hi,
since React-DateTime-Picker contains multiple input elements to achieve what it's made for, we couldn't use native event handler. I suggest you to curry your onChange function to achieve what you want:

```jsx
function makeOnChange(name) {
  return function onChange(value) {
    return { name, value };
  }
}

// Usage:
<DateTimePicker onChange={makeOnChange('myName1')} />
```
