### ISSUE TITLE
[Feature Request] Wrap-around input field values

### ISSUE THREAD

**Issue by marlberm2014** [wojtekmaj/react-datetime-picker#75]
Is it possible to have the input field to increment/decrement when using mouse wheel/keyboard up/keyboard down? For example I'm using the mouse wheel on the seconds field, continuously scrolling up, right now when I reach the maximum 59 seconds, it will stop there. Is it possible that instead of stopping at 59, it will wrap-around to 00 seconds and then increment the minutes field (if the minute is also max, it will cascade the change up to the next field, up to the year value).

**Comment by wojtekmaj** [comment]
That's not currently possible, but should be - as this package tries to follow native inputs as closely as possible. Adding to worklog.
