### ISSUE TITLE
can we block (disable) specific dates between minDate and maxDate

### ISSUE THREAD

**Issue by omarTherefore** [wojtekmaj/react-datetime-picker#76]
I am designing a web app for a store that has some blackout dates for pickup, but they fall within the acceptable range of dates ( > min date && < maxDate). i need to show them as disabled and disable selection on them.
is that possible?

**Comment by wojtekmaj** [comment]
Hi,
you can disable them in the calendar (refer to react-calendar docs), but not really in the input itself. Sorry about that!
