### ISSUE TITLE
How to change the icon of the Reset button ?

### ISSUE THREAD

**Issue by thanveershah** [wojtekmaj/react-datetime-picker#79]
Is there any way to change the icon of the Reset button ?

**Comment by wojtekmaj** [comment]
`clearIcon` prop, see README for details.

**Comment by thanveershah** [comment]
I checked, It shows to hide the icon , I want to change it to a different Icon , How do I do that

**Comment by wojtekmaj** [comment]
You pass something other than null as this prop value.
