### ISSUE TITLE
Support: Testing with testing-library/react

### ISSUE THREAD

**Issue by LeviButcher** [wojtekmaj/react-datetime-picker#81]
Problem: DateTimePicker does not render successfully when used with testing-library/react.

I couldn't find any filed issues of anyone using the DateTimePicker except for #68 but seems they were successful in using testing-library/react.

Here is a codesandbox link demonstrating it failing using the example provided in the readme.
https://codesandbox.io/s/fancy-pond-3n4x2?fontsize=14&hidenavigation=1&theme=dark

Love the date-picker, it's much better than any other solution.

**Comment by wojtekmaj** [comment]
Hi,
please see https://github.com/wojtekmaj/update-input-width/issues/2 for details on this error and a workaround. It's also the best place do discuss this issue and follow updates.

Thanks for the kind words, too!
