### ISSUE TITLE
Styling __inputGroup

### ISSUE THREAD

**Issue by BobbyWalker** [wojtekmaj/react-datetime-picker#83]
Is there a way to style the __inputGroup without resorting to a lot of !important class definitions?

Even using the nostyle option, all of the inputs are set at fixed widths so when I increase the font sizes I exceed the individual input components.

Thanks!

FWIW, I love this component.

**Comment by wojtekmaj** [comment]
Hi,
yes! You can load React-DateTime-Picker without the styles, download the originals (make sure to include React-Calendar's, too), edit them and include in your code manually! Yay open source!
