### ISSUE TITLE
Style does not match demo

### ISSUE THREAD

**Issue by murrayju** [wojtekmaj/react-datetime-picker#90]
The included styles look quite different from the demo page. I used create-react-app to start clean, and plop in a react-datetime-picker.

What I see:
![image](https://user-images.githubusercontent.com/508461/72024499-cd292200-3232-11ea-9385-c124fe2da044.png)

Demo:
![image](https://user-images.githubusercontent.com/508461/72024519-db773e00-3232-11ea-9b3e-28f499f3b02a.png)

It appears that many of the styles used in the demo do not appear in the source code. For example, the class `.react-datetime-picker--closed` in the demo gives rounded borders, while the included css contains no rules at all for this class.

Is this intentional, or is some stuff just missing from the source? Is there an easy way to apply the theme from the demo?

**Comment by wojtekmaj** [comment]
Hi,
yes - styles included are absolute minimum for it to work well, which makes it easy to customize which is what you are very likely to do when implementing React-DateTime-Picker in real application. Styles on demo page show what is possible to achieve. 

It's the same story with [React-Clock](http://projects.wojtekmaj.pl/react-clock) :)

If you're interested in stylesheet from my demo page, I can share it with you.

**Comment by jasoncui** [comment]
@wojtekmaj what would you recommend as the quickest and cleanest way to add custom styling for implementation in a basic React app?

**Comment by wojtekmaj** [comment]
@jasoncui Import React Date Picker without the styles, copy original styles from the repo to your project and edit it as you like it.

**Comment by alan-cooney** [comment]
> Hi,
> yes - styles included are absolute minimum for it to work well, which makes it easy to customize which is what you are very likely to do when implementing React-DateTime-Picker in real application. Styles on demo page show what is possible to achieve.
> 
> It's the same story with [React-Clock](http://projects.wojtekmaj.pl/react-clock) :)
> 
> If you're interested in stylesheet from my demo page, I can share it with you.

Yes please can you share these?

**Comment by wojtekmaj** [comment]
Sure thing, although it's quite complicated there, demo handles like 8 different projects.

https://gist.github.com/wojtekmaj/a36712e5f8ea6e035ef8d845ab246cd5

Good luck!
